// This file is generated by PolyFHE
#include <cuda.h>
#include <cuda_runtime.h>
#include <chrono>
#include <iostream>
#include <numeric>
#include <vector>
#include <stdio.h>
#include "polyfhe/kernel/device_context.hpp"
#include "polyfhe/kernel/polynomial.cuh"
#include "polyfhe/kernel/ntt.hpp"
#include "polyfhe/kernel/ntt-phantom.hpp"
#include "phantom-fhe/include/phantom.h"
#include "phantom-fhe/include/uintmodmath.cuh"
// Define kernel for subgraph[0], type: ElemLimb2
__global__ void Mult_1_iNTTPhase2_2(Params *params, int start_limb, int end_limb, uint64_t *edge_Init_0_6_Mult_1_0, uint64_t *edge_Init_0_7_Mult_1_1, uint64_t *edge_Mult_1_0_End_5_2, uint64_t *edge_iNTTPhase2_2_0_iNTTPhase1_3_0){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // Load data to register
        const int twr_idx = tid / params->N + start_limb;
        uint64_t *in = edge_Init_0_6_Mult_1_0 + twr_idx * params->N;
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + blockIdx.x * blockDim.x * 8 + threadIdx.x * 8 + l);
        }
        __syncthreads();
        size_t batch_idx = tid / n_tower;

        // Mult_1
        const size_t idx = blockIdx.x * blockDim.x * 8 + threadIdx.x * 8;
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = xxx_multiply_and_barrett_reduce_uint64(edge_Init_0_6_Mult_1_0[idx + l], edge_Init_0_7_Mult_1_1[idx + l], params->qVec[batch_idx], params->modulus_const_ratio + batch_idx * 2);
        }
        #pragma unroll
        for (int l = 0; l < 4; l++){
            asm("st.cs.global.v2.u64 [%0], {%1, %2};" :  : "l"(edge_Mult_1_0_End_5_2 + idx + 2 * l),"l"(reg[2 * l]),"l"(reg[2 * l + 1]));
        }

        // iNTTPhase2_2
        d_poly_inwt_radix8_phase2(params, 0, shared, reg, tid);

        // Store data from register
        const size_t n_group = params->n2 / 8;
        const size_t idx_base = start_limb * params->N + blockIdx.x * blockDim.x * params->per_thread_ntt_size + (threadIdx.x / n_group) * n_group * params->per_thread_ntt_size + (threadIdx.x % n_group);
        uint64_t *out = edge_iNTTPhase2_2_0_iNTTPhase1_3_0;
        #pragma unroll
        for (int l = 0; l < 8; l++){
            *(out + idx_base + n_group * l) = reg[l];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[1], type: ElemLimb1
__global__ void iNTTPhase1_3_MultConst_4(Params *params, int start_limb, int end_limb, uint64_t *edge_iNTTPhase2_2_0_iNTTPhase1_3_0, uint64_t *edge_MultConst_4_0_End_5_3, uint64_t *modup_mult, uint64_t *modup_mult_shoup){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    uint64_t *in = edge_iNTTPhase2_2_0_iNTTPhase1_3_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // iNTTPhase1_3
        d_poly_inplace_inwt_radix8_phase1(in, params, start_limb, shared, reg, i);
        // MultConst_4
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = xxx_multiply_and_reduce_shoup(reg[l], modup_mult[twr_idx], modup_mult_shoup[twr_idx], params->qVec[twr_idx]);
        }

        // Store data from register
        const size_t idx_out = twr_idx * params->N + n_init;
        out = edge_MultConst_4_0_End_5_3;
        #pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_out + n_twr * l) = reg[l];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[2], type: Elem
__global__ void Mult_8_Mult_6_Add_7(Params *params, int start_limb, int end_limb, uint64_t *edge_Init_0_2_Mult_8_0, uint64_t *edge_Init_0_3_Mult_8_1, uint64_t *edge_Init_0_4_Mult_6_0, uint64_t *edge_Init_0_5_Mult_6_1, uint64_t *edge_Add_7_0_End_5_0){
    extern __shared__ uint64_t shared[];
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        // Mult_8
        res = xxx_multiply_and_barrett_reduce_uint64(edge_Init_0_2_Mult_8_0[n_idx] , edge_Init_0_3_Mult_8_1[n_idx], q, params->modulus_const_ratio + l_idx * 2);
         shared[0 + threadIdx.x] = res;
        // Mult_6
        res = xxx_multiply_and_barrett_reduce_uint64(edge_Init_0_4_Mult_6_0[n_idx] , edge_Init_0_5_Mult_6_1[n_idx], q, params->modulus_const_ratio + l_idx * 2);
         shared[128 + threadIdx.x] = res;
        // Add_7
        res = shared[0 + threadIdx.x] + shared[128 + threadIdx.x];
        if (res >= q) res -= q;
        edge_Add_7_0_End_5_0[n_idx] = res;
    }
}


// Define kernel for subgraph[3], type: Elem
__global__ void Mult_9(Params *params, int start_limb, int end_limb, uint64_t *edge_Init_0_0_Mult_9_0, uint64_t *edge_Init_0_1_Mult_9_1, uint64_t *edge_Mult_9_0_End_5_1){
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        // Mult_9
        res = xxx_multiply_and_barrett_reduce_uint64(edge_Init_0_0_Mult_9_0[n_idx] , edge_Init_0_1_Mult_9_1[n_idx], q, params->modulus_const_ratio + l_idx * 2);
         edge_Mult_9_0_End_5_1[n_idx] = res;
    }
}


void entry_kernel(Params *params_d, Params *params_h, PhantomContext &context, uint64_t **relin_keys, uint64_t *in0, uint64_t *in1, uint64_t *out0, uint64_t *out1, bool if_benchmark, int n_opt){
    phantom::DRNSTool *rns_tool = params_h->rns_tools[1];

    // =====================================
    // Input arguments
    // =====================================
    // Edge: Init_0 -> Mult_9
    uint64_t *edge_Init_0_0_Mult_9_0_d = in0 + 0;
    // Edge: Init_0 -> Mult_9
    uint64_t *edge_Init_0_1_Mult_9_1_d = in1 + 0;
    // Edge: Init_0 -> Mult_8
    uint64_t *edge_Init_0_2_Mult_8_0_d = in0 + 0;
    // Edge: Init_0 -> Mult_8
    uint64_t *edge_Init_0_3_Mult_8_1_d = in1 + 1966080;
    // Edge: Init_0 -> Mult_6
    uint64_t *edge_Init_0_4_Mult_6_0_d = in0 + 1966080;
    // Edge: Init_0 -> Mult_6
    uint64_t *edge_Init_0_5_Mult_6_1_d = in1 + 0;
    // Edge: Init_0 -> Mult_1
    uint64_t *edge_Init_0_6_Mult_1_0_d = in0 + 1966080;
    // Edge: Init_0 -> Mult_1
    uint64_t *edge_Init_0_7_Mult_1_1_d = in1 + 1966080;

    // =====================================
    // Output arguments
    // =====================================
    // Edge: Add_7 -> End_5
    uint64_t *edge_Add_7_0_End_5_0_d = out0 + 1966080;
    // Edge: Mult_9 -> End_5
    uint64_t *edge_Mult_9_0_End_5_1_d = out0 + 0;
    // Edge: Mult_1 -> End_5
    uint64_t *edge_Mult_1_0_End_5_2_d = out0 + 3932160;
    // Edge: MultConst_4 -> End_5
    uint64_t *edge_MultConst_4_0_End_5_3_d = out1 + 0;

    // =====================================
    // Edges
    // Define global edges for GPU
    // =====================================
    uint64_t *edge_iNTTPhase2_2_0_iNTTPhase1_3_0_d = edge_MultConst_4_0_End_5_3_d;
    // =====================================
    std::cout << "### Warm up and Test" << std::endl;
    std::cout << "N : " << params_h->N << std::endl;
    std::cout << "L : " << params_h->L << std::endl;
    std::cout << "dnum : " << params_h->dnum << std::endl;
    std::cout << "K : " << params_h->K << std::endl;
    std::cout << "KL : " << params_h->KL << std::endl;
    std::cout << "alpha : " << params_h->alpha << std::endl;
    phantom::DRNSTool *drns_tool = params_h->rns_tools[1];
    const int beta = std::ceil(1.0 * params_h->L / params_h->alpha);
    std::cout << "beta: " << beta << std::endl;
    // ModUp
    uint64_t *modup_mult = rns_tool->partQlHatInv_mod_Ql_concat();
    uint64_t *modup_mult_shoup = rns_tool->partQlHatInv_mod_Ql_concat_shoup();
    // ModDown
    const DBaseConverter moddown_converter = drns_tool->base_P_to_Ql_conv();
    uint64_t *moddown_mult = moddown_converter.ibase().QHatInvModq();
    uint64_t *moddown_mult_shoup = moddown_converter.ibase().QHatInvModq_shoup();
    uint64_t *moddown_matmul = moddown_converter.QHatModp();


    // =====================================
    // Benchmark
    // =====================================
    if (if_benchmark){
        std::cout << "### Benchmark" << std::endl;
        std::vector<double> elapsed_times;
        for (int i = 0; i < 100; i++)
        {

            // Call kernel
            // Timer start
            auto start = std::chrono::high_resolution_clock::now();
            // const int current_limb = params_h->L;
            const int modup_limb = params_h->KL;
            Mult_1_iNTTPhase2_2<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, 0, 30, edge_Init_0_6_Mult_1_0_d, edge_Init_0_7_Mult_1_1_d, edge_Mult_1_0_End_5_2_d, edge_iNTTPhase2_2_0_iNTTPhase1_3_0_d);
            iNTTPhase1_3_MultConst_4<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, 0, 30, edge_iNTTPhase2_2_0_iNTTPhase1_3_0_d, edge_MultConst_4_0_End_5_3_d, modup_mult, modup_mult_shoup);
            Mult_8_Mult_6_Add_7<<<4096, 256, 3072>>>(params_d, 0, 30, edge_Init_0_2_Mult_8_0_d, edge_Init_0_3_Mult_8_1_d, edge_Init_0_4_Mult_6_0_d, edge_Init_0_5_Mult_6_1_d, edge_Add_7_0_End_5_0_d);
            Mult_9<<<4096, 256, 0>>>(params_d, 0, 30, edge_Init_0_0_Mult_9_0_d, edge_Init_0_1_Mult_9_1_d, edge_Mult_9_0_End_5_1_d);
            checkCudaErrors(cudaDeviceSynchronize());
            // Timer Stop
            checkCudaErrors(cudaDeviceSynchronize());
            auto end = std::chrono::high_resolution_clock::now();


            auto elapsed_usec = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
            std::cout << "Elapsed time: " << elapsed_usec.count() << "us" << std::endl;
            if (i != 0) {elapsed_times.push_back(elapsed_usec.count());}
        }
        std::cout << "Average time[us]: " << std::accumulate(elapsed_times.begin(), elapsed_times.end(), 0.0) / elapsed_times.size() << std::endl;
    }
}
