// This file is generated by PolyFHE
#include <cuda.h>
#include <cuda_runtime.h>
#include <stdio.h>

#include <chrono>
#include <iostream>
#include <numeric>
#include <vector>

#include "phantom-fhe/include/phantom.h"
#include "phantom-fhe/include/uintmodmath.cuh"
#include "polyfhe/kernel/device_context.hpp"
#include "polyfhe/kernel/ntt-phantom.hpp"
#include "polyfhe/kernel/ntt.hpp"
#include "polyfhe/kernel/polynomial.cuh"
// Define kernel for subgraph[0], type: Elem
__global__ void Mult_4_Mult_1_Add_2(Params *params,
                                    uint64_t *edge_Init_0_4_Mult_4_0,
                                    uint64_t *edge_Init_0_5_Mult_4_1,
                                    uint64_t *edge_Init_0_6_Mult_1_0,
                                    uint64_t *edge_Init_0_7_Mult_1_1,
                                    uint64_t *edge_Add_2_0_End_3_0) {
    extern __shared__ uint64_t shared[];
    const int start_limb = 0;
    const int end_limb = 30;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;
         idx < params->N * (end_limb - start_limb);
         idx += blockDim.x * gridDim.x) {
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        // Mult_4
        res = xxx_multiply_and_barrett_reduce_uint64(
            edge_Init_0_4_Mult_4_0[n_idx], edge_Init_0_5_Mult_4_1[n_idx], q,
            params->modulus_const_ratio + l_idx * 2);
        shared[0 + threadIdx.x] = res;
        // Mult_1
        res = xxx_multiply_and_barrett_reduce_uint64(
            edge_Init_0_6_Mult_1_0[n_idx], edge_Init_0_7_Mult_1_1[n_idx], q,
            params->modulus_const_ratio + l_idx * 2);
        shared[128 + threadIdx.x] = res;
        // Add_2
        res = shared[0 + threadIdx.x] + shared[128 + threadIdx.x];
        if (res >= q)
            res -= q;
        edge_Add_2_0_End_3_0[n_idx] = res;
    }
}

// Define kernel for subgraph[1], type: Elem
__global__ void Mult_5(Params *params, uint64_t *edge_Init_0_2_Mult_5_0,
                       uint64_t *edge_Init_0_3_Mult_5_1,
                       uint64_t *edge_Mult_5_0_End_3_1) {
    const int start_limb = 0;
    const int end_limb = 30;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;
         idx < params->N * (end_limb - start_limb);
         idx += blockDim.x * gridDim.x) {
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        // Mult_5
        res = xxx_multiply_and_barrett_reduce_uint64(
            edge_Init_0_2_Mult_5_0[n_idx], edge_Init_0_3_Mult_5_1[n_idx], q,
            params->modulus_const_ratio + l_idx * 2);
        edge_Mult_5_0_End_3_1[n_idx] = res;
    }
}

// Define kernel for subgraph[2], type: ElemLimb2
__global__ void Mult_6_iNTTPhase2_7(
    Params *params, uint64_t *edge_Init_0_0_Mult_6_0,
    uint64_t *edge_Init_0_1_Mult_6_1, uint64_t *edge_Mult_6_0_End_3_2,
    uint64_t *edge_iNTTPhase2_7_0_iNTTPhase1_8_0) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 30;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x;
         tid < (end_limb - start_limb) * n_tower;
         tid += blockDim.x * gridDim.x) {
        // Load data to register
        const int twr_idx = tid / n_tower + start_limb;
        uint64_t *in = edge_Init_0_0_Mult_6_0;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            reg[l] = *(in + blockIdx.x * blockDim.x * 8 + threadIdx.x * 8 + l);
        }
        __syncthreads();
        size_t batch_idx = tid / n_tower;

        // Mult_6
        const size_t idx = blockIdx.x * blockDim.x * 8 + threadIdx.x * 8;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            reg[l] = xxx_multiply_and_barrett_reduce_uint64(
                edge_Init_0_0_Mult_6_0[idx + l],
                edge_Init_0_1_Mult_6_1[idx + l], params->qVec[batch_idx],
                params->modulus_const_ratio + batch_idx * 2);
        }
#pragma unroll
        for (int l = 0; l < 4; l++) {
            asm("st.cs.global.v2.u64 [%0], {%1, %2};"
                :
                : "l"(edge_Mult_6_0_End_3_2 + idx + 2 * l), "l"(reg[2 * l]),
                  "l"(reg[2 * l + 1]));
        }

        // iNTTPhase2_7
        d_poly_inwt_radix8_phase2(params, 0, shared, reg, tid);

        // Store data from register
        const size_t n_group = params->n2 / 8;
        const size_t idx_base =
            start_limb * params->N +
            blockIdx.x * blockDim.x * params->per_thread_ntt_size +
            (threadIdx.x / n_group) * n_group * params->per_thread_ntt_size +
            (threadIdx.x % n_group);
        uint64_t *out = edge_iNTTPhase2_7_0_iNTTPhase1_8_0;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_base + n_group * l) = reg[l];
        }
        __syncthreads();
    }
}

// Define kernel for subgraph[3], type: ElemLimb1
__global__ void iNTTPhase1_8_MultConst_9(
    Params *params, uint64_t *edge_iNTTPhase2_7_0_iNTTPhase1_8_0,
    uint64_t *edge_MultConst_9_0_BConv_35_0,
    uint64_t *edge_MultConst_9_1_BConv_32_0,
    uint64_t *edge_MultConst_9_2_BConv_29_0,
    uint64_t *edge_MultConst_9_3_BConv_26_0,
    uint64_t *edge_MultConst_9_4_BConv_10_0, uint64_t *modup_mult,
    uint64_t *modup_mult_shoup) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 30;
    uint64_t *in = edge_iNTTPhase2_7_0_iNTTPhase1_8_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x;
         i < (params->N / 8 * (end_limb - start_limb));
         i += blockDim.x * gridDim.x) {
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid +
                              params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // iNTTPhase1_8
        d_poly_inplace_inwt_radix8_phase1(in, params, start_limb, shared, reg,
                                          i);
// MultConst_9
#pragma unroll
        for (int l = 0; l < 8; l++) {
            reg[l] = xxx_multiply_and_reduce_shoup(reg[l], modup_mult[twr_idx],
                                                   modup_mult_shoup[twr_idx],
                                                   params->qVec[twr_idx]);
        }

        // Store data from register
        const size_t idx_out = twr_idx * params->N + n_init;
        out = edge_MultConst_9_0_BConv_35_0;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_out + n_twr * l) = reg[l];
        }
        __syncthreads();
    }
}

// Define kernel for subgraph[20], type: ElemLimb2
__global__ void iNTTPhase2_14(Params *params,
                              uint64_t *edge_MultKeyAccum_13_1_iNTTPhase2_14_0,
                              uint64_t *edge_iNTTPhase2_14_0_iNTTPhase1_15_0) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 30;
    const int end_limb = 36;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x;
         tid < (end_limb - start_limb) * n_tower;
         tid += blockDim.x * gridDim.x) {
        // Load data to register
        const int twr_idx = tid / n_tower + start_limb;
        uint64_t *in = edge_MultKeyAccum_13_1_iNTTPhase2_14_0;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            reg[l] = *(in + blockIdx.x * blockDim.x * 8 + threadIdx.x * 8 + l);
        }
        __syncthreads();

        // iNTTPhase2_14
        d_poly_inwt_radix8_phase2(params, 30, shared, reg, tid);

        // Store data from register
        const size_t n_group = params->n2 / 8;
        const size_t idx_base =
            start_limb * params->N +
            blockIdx.x * blockDim.x * params->per_thread_ntt_size +
            (threadIdx.x / n_group) * n_group * params->per_thread_ntt_size +
            (threadIdx.x % n_group);
        uint64_t *out = edge_iNTTPhase2_14_0_iNTTPhase1_15_0;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_base + n_group * l) = reg[l];
        }
        __syncthreads();
    }
}

// Define kernel for subgraph[21], type: ElemLimb1
__global__ void iNTTPhase1_15_MultConst_16(
    Params *params, uint64_t *edge_iNTTPhase2_14_0_iNTTPhase1_15_0,
    uint64_t *edge_MultConst_16_0_Unknown_17_0, uint64_t *moddown_mult,
    uint64_t *moddown_mult_shoup) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 30;
    const int end_limb = 36;
    uint64_t *in = edge_iNTTPhase2_14_0_iNTTPhase1_15_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x;
         i < (params->N / 8 * (end_limb - start_limb));
         i += blockDim.x * gridDim.x) {
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid +
                              params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // iNTTPhase1_15
        d_poly_inplace_inwt_radix8_phase1(in, params, start_limb, shared, reg,
                                          i);
// MultConst_16
#pragma unroll
        for (int l = 0; l < 8; l++) {
            reg[l] = xxx_multiply_and_reduce_shoup(
                reg[l], moddown_mult[twr_idx - start_limb],
                moddown_mult_shoup[twr_idx - start_limb],
                params->qVec[twr_idx]);
        }

        // Store data from register
        const size_t idx_out = twr_idx * params->N + n_init;
        out = edge_MultConst_16_0_Unknown_17_0;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_out + n_twr * l) = reg[l];
        }
        __syncthreads();
    }
}

// Define kernel for subgraph[23], type: ElemLimb1
__global__ void NTTPhase1_18(Params *params,
                             uint64_t *edge_Unknown_17_0_NTTPhase1_18_0,
                             uint64_t *edge_NTTPhase1_18_0_NTTPhase2_19_0,
                             const uint64_t *twiddles,
                             const uint64_t *twiddles_shoup,
                             const DModulus *modulus) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 30;
    uint64_t *in = edge_Unknown_17_0_NTTPhase1_18_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x;
         i < (params->N / 8 * (end_limb - start_limb));
         i += blockDim.x * gridDim.x) {
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid +
                              params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
// NTTPhase1_18

// Load to register
#pragma unroll
        for (int l = 0; l < 8; l++) {
            reg[l] = *(in + twr_idx * params->N + n_init + n_twr * l);
        }
        out = edge_NTTPhase1_18_0_NTTPhase2_19_0;
        d_poly_fnwt_phase1(params, out, shared, reg, twiddles, twiddles_shoup,
                           modulus, twr_idx, twr_idx, n_init, i);
    }
}

// Define kernel for subgraph[24], type: ElemLimb2
__global__ void NTTPhase2_19(Params *params,
                             uint64_t *edge_NTTPhase1_18_0_NTTPhase2_19_0,
                             uint64_t *edge_NTTPhase2_19_0_End_3_4,
                             const uint64_t *twiddles,
                             const uint64_t *twiddles_shoup,
                             const DModulus *modulus) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 30;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x;
         tid < (end_limb - start_limb) * n_tower;
         tid += blockDim.x * gridDim.x) {
        // NTTPhase2_19
        size_t twr_idx = end_limb - 1 - (tid / n_tower) + start_limb;
        uint64_t n_init;
        d_poly_fnwt_phase2(params, edge_NTTPhase1_18_0_NTTPhase2_19_0, shared,
                           reg, twiddles, twiddles_shoup, modulus, end_limb,
                           start_limb, twr_idx, twr_idx, &n_init, tid);
        uint64_t *out_ptr = edge_NTTPhase2_19_0_End_3_4 + twr_idx * params->N;
#pragma unroll
        for (size_t j = 0; j < 8; j++) {
            *(out_ptr + n_init + params->n2 / 8 * j) = reg[j];
        }
        __syncthreads();
    }
}

// Define kernel for subgraph[25], type: ElemLimb2
__global__ void iNTTPhase2_20(Params *params,
                              uint64_t *edge_MultKeyAccum_13_0_iNTTPhase2_20_0,
                              uint64_t *edge_iNTTPhase2_20_0_iNTTPhase1_21_0) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 30;
    const int end_limb = 36;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x;
         tid < (end_limb - start_limb) * n_tower;
         tid += blockDim.x * gridDim.x) {
        // Load data to register
        const int twr_idx = tid / n_tower + start_limb;
        uint64_t *in = edge_MultKeyAccum_13_0_iNTTPhase2_20_0;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            reg[l] = *(in + blockIdx.x * blockDim.x * 8 + threadIdx.x * 8 + l);
        }
        __syncthreads();

        // iNTTPhase2_20
        d_poly_inwt_radix8_phase2(params, 30, shared, reg, tid);

        // Store data from register
        const size_t n_group = params->n2 / 8;
        const size_t idx_base =
            start_limb * params->N +
            blockIdx.x * blockDim.x * params->per_thread_ntt_size +
            (threadIdx.x / n_group) * n_group * params->per_thread_ntt_size +
            (threadIdx.x % n_group);
        uint64_t *out = edge_iNTTPhase2_20_0_iNTTPhase1_21_0;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_base + n_group * l) = reg[l];
        }
        __syncthreads();
    }
}

// Define kernel for subgraph[26], type: ElemLimb1
__global__ void iNTTPhase1_21_MultConst_22(
    Params *params, uint64_t *edge_iNTTPhase2_20_0_iNTTPhase1_21_0,
    uint64_t *edge_MultConst_22_0_Unknown_23_0, uint64_t *moddown_mult,
    uint64_t *moddown_mult_shoup) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 30;
    const int end_limb = 36;
    uint64_t *in = edge_iNTTPhase2_20_0_iNTTPhase1_21_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x;
         i < (params->N / 8 * (end_limb - start_limb));
         i += blockDim.x * gridDim.x) {
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid +
                              params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // iNTTPhase1_21
        d_poly_inplace_inwt_radix8_phase1(in, params, start_limb, shared, reg,
                                          i);
// MultConst_22
#pragma unroll
        for (int l = 0; l < 8; l++) {
            reg[l] = xxx_multiply_and_reduce_shoup(
                reg[l], moddown_mult[twr_idx - start_limb],
                moddown_mult_shoup[twr_idx - start_limb],
                params->qVec[twr_idx]);
        }

        // Store data from register
        const size_t idx_out = twr_idx * params->N + n_init;
        out = edge_MultConst_22_0_Unknown_23_0;
#pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_out + n_twr * l) = reg[l];
        }
        __syncthreads();
    }
}

// Define kernel for subgraph[28], type: ElemLimb1
__global__ void NTTPhase1_24(Params *params,
                             uint64_t *edge_Unknown_23_0_NTTPhase1_24_0,
                             uint64_t *edge_NTTPhase1_24_0_NTTPhase2_25_0,
                             const uint64_t *twiddles,
                             const uint64_t *twiddles_shoup,
                             const DModulus *modulus) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 30;
    uint64_t *in = edge_Unknown_23_0_NTTPhase1_24_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x;
         i < (params->N / 8 * (end_limb - start_limb));
         i += blockDim.x * gridDim.x) {
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid +
                              params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
// NTTPhase1_24

// Load to register
#pragma unroll
        for (int l = 0; l < 8; l++) {
            reg[l] = *(in + twr_idx * params->N + n_init + n_twr * l);
        }
        out = edge_NTTPhase1_24_0_NTTPhase2_25_0;
        d_poly_fnwt_phase1(params, out, shared, reg, twiddles, twiddles_shoup,
                           modulus, twr_idx, twr_idx, n_init, i);
    }
}

// Define kernel for subgraph[29], type: ElemLimb2
__global__ void NTTPhase2_25(Params *params,
                             uint64_t *edge_NTTPhase1_24_0_NTTPhase2_25_0,
                             uint64_t *edge_NTTPhase2_25_0_End_3_3,
                             const uint64_t *twiddles,
                             const uint64_t *twiddles_shoup,
                             const DModulus *modulus) {
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 30;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x;
         tid < (end_limb - start_limb) * n_tower;
         tid += blockDim.x * gridDim.x) {
        // NTTPhase2_25
        size_t twr_idx = end_limb - 1 - (tid / n_tower) + start_limb;
        uint64_t n_init;
        d_poly_fnwt_phase2(params, edge_NTTPhase1_24_0_NTTPhase2_25_0, shared,
                           reg, twiddles, twiddles_shoup, modulus, end_limb,
                           start_limb, twr_idx, twr_idx, &n_init, tid);
        uint64_t *out_ptr = edge_NTTPhase2_25_0_End_3_3 + twr_idx * params->N;
#pragma unroll
        for (size_t j = 0; j < 8; j++) {
            *(out_ptr + n_init + params->n2 / 8 * j) = reg[j];
        }
        __syncthreads();
    }
}

void entry_kernel(Params *params_d, Params *params_h, PhantomContext &context,
                  uint64_t **relin_keys, uint64_t *in0, uint64_t *in1,
                  uint64_t *out0, uint64_t *out1, bool if_benchmark,
                  int n_opt) {
    phantom::DRNSTool *rns_tool = params_h->rns_tools[1];

    // =====================================
    // Input arguments
    // =====================================
    // Edge: Init_0 -> Mult_6
    uint64_t *edge_Init_0_0_Mult_6_0_d = in0 + 1966080;
    // Edge: Init_0 -> Mult_6
    uint64_t *edge_Init_0_1_Mult_6_1_d = in1 + 1966080;
    // Edge: Init_0 -> Mult_5
    uint64_t *edge_Init_0_2_Mult_5_0_d = in0 + 0;
    // Edge: Init_0 -> Mult_5
    uint64_t *edge_Init_0_3_Mult_5_1_d = in1 + 0;
    // Edge: Init_0 -> Mult_4
    uint64_t *edge_Init_0_4_Mult_4_0_d = in0 + 0;
    // Edge: Init_0 -> Mult_4
    uint64_t *edge_Init_0_5_Mult_4_1_d = in1 + 1966080;
    // Edge: Init_0 -> Mult_1
    uint64_t *edge_Init_0_6_Mult_1_0_d = in0 + 1966080;
    // Edge: Init_0 -> Mult_1
    uint64_t *edge_Init_0_7_Mult_1_1_d = in1 + 0;

    // =====================================
    // Output arguments
    // =====================================
    // Edge: Add_2 -> End_3
    uint64_t *edge_Add_2_0_End_3_0_d = out0 + 1966080;
    // Edge: Mult_5 -> End_3
    uint64_t *edge_Mult_5_0_End_3_1_d = out0 + 0;
    // Edge: Mult_6 -> End_3
    uint64_t *edge_Mult_6_0_End_3_2_d = out0 + 3932160;
    // Edge: NTTPhase2_25 -> End_3
    uint64_t *edge_NTTPhase2_25_0_End_3_3_d = out1 + 0;
    // Edge: NTTPhase2_19 -> End_3
    uint64_t *edge_NTTPhase2_19_0_End_3_4_d = out1 + 2359296;

    // =====================================
    // Edges
    // Define global edges for GPU
    // =====================================
    // Edge: iNTTPhase2_7 -> iNTTPhase1_8
    uint64_t *edge_iNTTPhase2_7_0_iNTTPhase1_8_0_d;
    checkCudaErrors(cudaMalloc((void **) &edge_iNTTPhase2_7_0_iNTTPhase1_8_0_d,
                               30 * params_h->N * sizeof(uint64_t)));
    // Edge: MultConst_9 -> BConv_35
    uint64_t *edge_MultConst_9_0_BConv_35_0_d;
    checkCudaErrors(cudaMalloc((void **) &edge_MultConst_9_0_BConv_35_0_d,
                               36 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_37 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_37_0_MultKeyAccum_13_0_d;
    checkCudaErrors(
        cudaMalloc((void **) &edge_NTTPhase2_37_0_MultKeyAccum_13_0_d,
                   36 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_34 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_34_0_MultKeyAccum_13_1_d;
    checkCudaErrors(
        cudaMalloc((void **) &edge_NTTPhase2_34_0_MultKeyAccum_13_1_d,
                   36 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_31 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_31_0_MultKeyAccum_13_2_d;
    checkCudaErrors(
        cudaMalloc((void **) &edge_NTTPhase2_31_0_MultKeyAccum_13_2_d,
                   36 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_28 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_28_0_MultKeyAccum_13_3_d;
    checkCudaErrors(
        cudaMalloc((void **) &edge_NTTPhase2_28_0_MultKeyAccum_13_3_d,
                   36 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_12 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_12_0_MultKeyAccum_13_4_d;
    checkCudaErrors(
        cudaMalloc((void **) &edge_NTTPhase2_12_0_MultKeyAccum_13_4_d,
                   36 * params_h->N * sizeof(uint64_t)));
    uint64_t *edge_MultConst_9_1_BConv_32_0_d = edge_MultConst_9_0_BConv_35_0_d;
    uint64_t *edge_MultConst_9_2_BConv_29_0_d = edge_MultConst_9_0_BConv_35_0_d;
    uint64_t *edge_MultConst_9_3_BConv_26_0_d = edge_MultConst_9_0_BConv_35_0_d;
    uint64_t *edge_MultConst_9_4_BConv_10_0_d = edge_MultConst_9_0_BConv_35_0_d;
    uint64_t *edge_BConv_35_0_NTTPhase1_36_0_d =
        edge_NTTPhase2_37_0_MultKeyAccum_13_0_d;
    uint64_t *edge_BConv_32_0_NTTPhase1_33_0_d =
        edge_NTTPhase2_34_0_MultKeyAccum_13_1_d;
    uint64_t *edge_BConv_29_0_NTTPhase1_30_0_d =
        edge_NTTPhase2_31_0_MultKeyAccum_13_2_d;
    uint64_t *edge_BConv_26_0_NTTPhase1_27_0_d =
        edge_NTTPhase2_28_0_MultKeyAccum_13_3_d;
    uint64_t *edge_BConv_10_0_NTTPhase1_11_0_d =
        edge_NTTPhase2_12_0_MultKeyAccum_13_4_d;
    uint64_t *edge_NTTPhase1_36_0_NTTPhase2_37_0_d =
        edge_NTTPhase2_37_0_MultKeyAccum_13_0_d;
    uint64_t *edge_NTTPhase1_33_0_NTTPhase2_34_0_d =
        edge_NTTPhase2_34_0_MultKeyAccum_13_1_d;
    uint64_t *edge_NTTPhase1_30_0_NTTPhase2_31_0_d =
        edge_NTTPhase2_31_0_MultKeyAccum_13_2_d;
    uint64_t *edge_NTTPhase1_27_0_NTTPhase2_28_0_d =
        edge_NTTPhase2_28_0_MultKeyAccum_13_3_d;
    uint64_t *edge_NTTPhase1_11_0_NTTPhase2_12_0_d =
        edge_NTTPhase2_12_0_MultKeyAccum_13_4_d;
    uint64_t *edge_MultKeyAccum_13_0_iNTTPhase2_20_0_d =
        edge_NTTPhase2_25_0_End_3_3_d;
    uint64_t *edge_MultKeyAccum_13_1_iNTTPhase2_14_0_d =
        edge_NTTPhase2_19_0_End_3_4_d;
    uint64_t *edge_iNTTPhase2_14_0_iNTTPhase1_15_0_d =
        edge_NTTPhase2_19_0_End_3_4_d;
    uint64_t *edge_MultConst_16_0_Unknown_17_0_d =
        edge_NTTPhase2_19_0_End_3_4_d;
    uint64_t *edge_Unknown_17_0_NTTPhase1_18_0_d =
        edge_NTTPhase2_19_0_End_3_4_d;
    uint64_t *edge_NTTPhase1_18_0_NTTPhase2_19_0_d =
        edge_NTTPhase2_19_0_End_3_4_d;
    uint64_t *edge_iNTTPhase2_20_0_iNTTPhase1_21_0_d =
        edge_NTTPhase2_25_0_End_3_3_d;
    uint64_t *edge_MultConst_22_0_Unknown_23_0_d =
        edge_NTTPhase2_25_0_End_3_3_d;
    uint64_t *edge_Unknown_23_0_NTTPhase1_24_0_d =
        edge_NTTPhase2_25_0_End_3_3_d;
    uint64_t *edge_NTTPhase1_24_0_NTTPhase2_25_0_d =
        edge_NTTPhase2_25_0_End_3_3_d;
    // =====================================
    std::cout << "### Warm up and Test" << std::endl;
    std::cout << "N : " << params_h->N << std::endl;
    std::cout << "L : " << params_h->L << std::endl;
    std::cout << "dnum : " << params_h->dnum << std::endl;
    std::cout << "K : " << params_h->K << std::endl;
    std::cout << "KL : " << params_h->KL << std::endl;
    std::cout << "alpha : " << params_h->alpha << std::endl;
    phantom::DRNSTool *drns_tool = params_h->rns_tools[1];
    const int beta = std::ceil(1.0 * params_h->L / params_h->alpha);
    std::cout << "beta: " << beta << std::endl;
    // ModUp
    uint64_t *modup_mult = rns_tool->partQlHatInv_mod_Ql_concat();
    uint64_t *modup_mult_shoup = rns_tool->partQlHatInv_mod_Ql_concat_shoup();
    // ModDown
    const DBaseConverter moddown_converter = drns_tool->base_P_to_Ql_conv();
    uint64_t *moddown_mult = moddown_converter.ibase().QHatInvModq();
    uint64_t *moddown_mult_shoup =
        moddown_converter.ibase().QHatInvModq_shoup();
    uint64_t *moddown_matmul = moddown_converter.QHatModp();
    // BConv input
    uint64_t **bconv_in_list = new uint64_t *[beta];
    bconv_in_list[0] = edge_MultConst_9_0_BConv_35_0_d;
    bconv_in_list[1] = edge_MultConst_9_1_BConv_32_0_d;
    bconv_in_list[2] = edge_MultConst_9_2_BConv_29_0_d;
    bconv_in_list[3] = edge_MultConst_9_3_BConv_26_0_d;
    bconv_in_list[4] = edge_MultConst_9_4_BConv_10_0_d;
    uint64_t **d_bconv_in_list;
    checkCudaErrors(
        cudaMalloc((void ***) &d_bconv_in_list, beta * sizeof(uint64_t *)));
    checkCudaErrors(cudaMemcpy(d_bconv_in_list, bconv_in_list,
                               beta * sizeof(uint64_t *),
                               cudaMemcpyHostToDevice));

    // BConv output
    uint64_t **bconv_out_list = new uint64_t *[beta];
    bconv_out_list[0] = edge_BConv_35_0_NTTPhase1_36_0_d;
    bconv_out_list[1] = edge_BConv_32_0_NTTPhase1_33_0_d;
    bconv_out_list[2] = edge_BConv_29_0_NTTPhase1_30_0_d;
    bconv_out_list[3] = edge_BConv_26_0_NTTPhase1_27_0_d;
    bconv_out_list[4] = edge_BConv_10_0_NTTPhase1_11_0_d;
    uint64_t **d_bconv_out_list;
    checkCudaErrors(
        cudaMalloc((void ***) &d_bconv_out_list, beta * sizeof(uint64_t *)));
    checkCudaErrors(cudaMemcpy(d_bconv_out_list, bconv_out_list,
                               beta * sizeof(uint64_t *),
                               cudaMemcpyHostToDevice));

    // NTT inout
    uint64_t **ntt_in_list = new uint64_t *[beta];
    ntt_in_list[0] = edge_NTTPhase1_36_0_NTTPhase2_37_0_d;
    ntt_in_list[1] = edge_NTTPhase1_33_0_NTTPhase2_34_0_d;
    ntt_in_list[2] = edge_NTTPhase1_30_0_NTTPhase2_31_0_d;
    ntt_in_list[3] = edge_NTTPhase1_27_0_NTTPhase2_28_0_d;
    ntt_in_list[4] = edge_NTTPhase1_11_0_NTTPhase2_12_0_d;
    uint64_t **d_ntt_in_list;
    checkCudaErrors(
        cudaMalloc((void ***) &d_ntt_in_list, beta * sizeof(uint64_t *)));
    checkCudaErrors(cudaMemcpy(d_ntt_in_list, ntt_in_list,
                               beta * sizeof(uint64_t *),
                               cudaMemcpyHostToDevice));

    // Accum input
    uint64_t **accum_in_list = new uint64_t *[beta];
    accum_in_list[0] = edge_NTTPhase2_37_0_MultKeyAccum_13_0_d;
    accum_in_list[1] = edge_NTTPhase2_34_0_MultKeyAccum_13_1_d;
    accum_in_list[2] = edge_NTTPhase2_31_0_MultKeyAccum_13_2_d;
    accum_in_list[3] = edge_NTTPhase2_28_0_MultKeyAccum_13_3_d;
    accum_in_list[4] = edge_NTTPhase2_12_0_MultKeyAccum_13_4_d;
    uint64_t **d_accum_in_list;
    checkCudaErrors(
        cudaMalloc((void ***) &d_accum_in_list, beta * sizeof(uint64_t *)));
    checkCudaErrors(cudaMemcpy(d_accum_in_list, accum_in_list,
                               beta * sizeof(uint64_t *),
                               cudaMemcpyHostToDevice));

    // qHatModp
    uint64_t **qhat_modp_list = new uint64_t *[beta];
    for (int j = 0; j < beta; j++) {
        qhat_modp_list[j] =
            drns_tool->v_base_part_Ql_to_compl_part_QlP_conv()[j].QHatModp();
    }
    uint64_t **d_qhat_modp_list;
    checkCudaErrors(
        cudaMalloc((void **) &d_qhat_modp_list, sizeof(uint64_t *) * beta));
    checkCudaErrors(cudaMemcpy(d_qhat_modp_list, qhat_modp_list,
                               sizeof(uint64_t *) * beta,
                               cudaMemcpyHostToDevice));

    // =====================================
    // Benchmark
    // =====================================
    if (if_benchmark) {
        std::cout << "### Benchmark" << std::endl;
        std::vector<double> elapsed_times;
        for (int i = 0; i < 10; i++) {
            // Call kernel
            // Timer start
            auto start = std::chrono::high_resolution_clock::now();
            // const int current_limb = params_h->L;
            const int modup_limb = params_h->KL;
            Mult_4_Mult_1_Add_2<<<4096, 256, 3072>>>(
                params_d, edge_Init_0_4_Mult_4_0_d, edge_Init_0_5_Mult_4_1_d,
                edge_Init_0_6_Mult_1_0_d, edge_Init_0_7_Mult_1_1_d,
                edge_Add_2_0_End_3_0_d);
            Mult_5<<<4096, 256, 0>>>(params_d, edge_Init_0_2_Mult_5_0_d,
                                     edge_Init_0_3_Mult_5_1_d,
                                     edge_Mult_5_0_End_3_1_d);
            Mult_6_iNTTPhase2_7<<<4096, 128,
                                  params_h->per_thread_ntt_size * 128 *
                                      sizeof(uint64_t)>>>(
                params_d, edge_Init_0_0_Mult_6_0_d, edge_Init_0_1_Mult_6_1_d,
                edge_Mult_6_0_End_3_2_d, edge_iNTTPhase2_7_0_iNTTPhase1_8_0_d);
            iNTTPhase1_8_MultConst_9<<<4096, (params_h->n1 / 8) * params_h->pad,
                                       (params_h->n1 + params_h->pad + 1) *
                                           params_h->pad * sizeof(uint64_t)>>>(
                params_d, edge_iNTTPhase2_7_0_iNTTPhase1_8_0_d,
                edge_MultConst_9_0_BConv_35_0_d,
                edge_MultConst_9_1_BConv_32_0_d,
                edge_MultConst_9_2_BConv_29_0_d,
                edge_MultConst_9_3_BConv_26_0_d,
                edge_MultConst_9_4_BConv_10_0_d, modup_mult, modup_mult_shoup);
            const int limb_per = params_h->alpha * n_opt;
            int n_divide_ = std::ceil(1.0 * modup_limb / limb_per);
            for (int iter = 0; iter < n_divide_; iter++) {
                int start_li = iter * limb_per;
                int end_li = (iter + 1) * limb_per;
                BConv_general_part_allbeta<<<4096, 128>>>(
                    params_d, d_bconv_in_list, d_bconv_out_list,
                    d_qhat_modp_list, params_h->alpha, start_li, limb_per,
                    params_h->alpha, beta, params_h->ntt_tables->twiddle(),
                    params_h->ntt_tables->twiddle_shoup(),
                    params_h->ntt_tables->modulus(), n_opt);
                NTTP1_part_allbeta_smem<<<4096, 128,
                                          (params_h->n1 + params_h->pad + 1) *
                                              params_h->pad *
                                              sizeof(uint64_t)>>>(
                    params_d, start_li, end_li, 0, modup_limb, params_h->K,
                    beta, params_h->ntt_tables->twiddle(),
                    params_h->ntt_tables->twiddle_shoup(),
                    params_h->ntt_tables->modulus(), d_accum_in_list);
                NTTP2_MultKeyAccum_part<<<4096, 128,
                                          8 * 128 * sizeof(uint64_t)>>>(
                    params_d, start_li, end_li, 0, modup_limb, params_h->K,
                    beta, params_h->ntt_tables->twiddle(),
                    params_h->ntt_tables->twiddle_shoup(),
                    params_h->ntt_tables->modulus(), d_accum_in_list,
                    edge_MultKeyAccum_13_0_iNTTPhase2_20_0_d,
                    edge_MultKeyAccum_13_1_iNTTPhase2_14_0_d, relin_keys);
            }
            iNTTPhase2_14<<<4096, 128,
                            params_h->per_thread_ntt_size * 128 *
                                sizeof(uint64_t)>>>(
                params_d, edge_MultKeyAccum_13_1_iNTTPhase2_14_0_d,
                edge_iNTTPhase2_14_0_iNTTPhase1_15_0_d);
            iNTTPhase1_15_MultConst_16<<<
                4096, (params_h->n1 / 8) * params_h->pad,
                (params_h->n1 + params_h->pad + 1) * params_h->pad *
                    sizeof(uint64_t)>>>(params_d,
                                        edge_iNTTPhase2_14_0_iNTTPhase1_15_0_d,
                                        edge_MultConst_16_0_Unknown_17_0_d,
                                        moddown_mult, moddown_mult_shoup);
            BConv_general<<<4096, 128>>>(
                params_d, edge_MultConst_16_0_Unknown_17_0_d,
                edge_Unknown_17_0_NTTPhase1_18_0_d, moddown_matmul, 30, 6, 0,
                30, params_h->ntt_tables->twiddle(),
                params_h->ntt_tables->twiddle_shoup(),
                params_h->ntt_tables->modulus());
            NTTPhase1_18<<<4096, (params_h->n1 / 8) * params_h->pad,
                           (params_h->n1 + params_h->pad + 1) * params_h->pad *
                               sizeof(uint64_t)>>>(
                params_d, edge_Unknown_17_0_NTTPhase1_18_0_d,
                edge_NTTPhase1_18_0_NTTPhase2_19_0_d,
                params_h->ntt_tables->twiddle(),
                params_h->ntt_tables->twiddle_shoup(),
                params_h->ntt_tables->modulus());
            NTTPhase2_19<<<4096, 128,
                           params_h->per_thread_ntt_size * 128 *
                               sizeof(uint64_t)>>>(
                params_d, edge_NTTPhase1_18_0_NTTPhase2_19_0_d,
                edge_NTTPhase2_19_0_End_3_4_d, params_h->ntt_tables->twiddle(),
                params_h->ntt_tables->twiddle_shoup(),
                params_h->ntt_tables->modulus());
            iNTTPhase2_20<<<4096, 128,
                            params_h->per_thread_ntt_size * 128 *
                                sizeof(uint64_t)>>>(
                params_d, edge_MultKeyAccum_13_0_iNTTPhase2_20_0_d,
                edge_iNTTPhase2_20_0_iNTTPhase1_21_0_d);
            iNTTPhase1_21_MultConst_22<<<
                4096, (params_h->n1 / 8) * params_h->pad,
                (params_h->n1 + params_h->pad + 1) * params_h->pad *
                    sizeof(uint64_t)>>>(params_d,
                                        edge_iNTTPhase2_20_0_iNTTPhase1_21_0_d,
                                        edge_MultConst_22_0_Unknown_23_0_d,
                                        moddown_mult, moddown_mult_shoup);
            BConv_general<<<4096, 128>>>(
                params_d, edge_MultConst_22_0_Unknown_23_0_d,
                edge_Unknown_23_0_NTTPhase1_24_0_d, moddown_matmul, 30, 6, 0,
                30, params_h->ntt_tables->twiddle(),
                params_h->ntt_tables->twiddle_shoup(),
                params_h->ntt_tables->modulus());
            NTTPhase1_24<<<4096, (params_h->n1 / 8) * params_h->pad,
                           (params_h->n1 + params_h->pad + 1) * params_h->pad *
                               sizeof(uint64_t)>>>(
                params_d, edge_Unknown_23_0_NTTPhase1_24_0_d,
                edge_NTTPhase1_24_0_NTTPhase2_25_0_d,
                params_h->ntt_tables->twiddle(),
                params_h->ntt_tables->twiddle_shoup(),
                params_h->ntt_tables->modulus());
            NTTPhase2_25<<<4096, 128,
                           params_h->per_thread_ntt_size * 128 *
                               sizeof(uint64_t)>>>(
                params_d, edge_NTTPhase1_24_0_NTTPhase2_25_0_d,
                edge_NTTPhase2_25_0_End_3_3_d, params_h->ntt_tables->twiddle(),
                params_h->ntt_tables->twiddle_shoup(),
                params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            // Timer Stop
            checkCudaErrors(cudaDeviceSynchronize());
            auto end = std::chrono::high_resolution_clock::now();

            auto elapsed_usec =
                std::chrono::duration_cast<std::chrono::microseconds>(end -
                                                                      start);
            std::cout << "Elapsed time: " << elapsed_usec.count() << "us"
                      << std::endl;
            if (i != 0) {
                elapsed_times.push_back(elapsed_usec.count());
            }
        }
        std::cout << "Average time[us]: "
                  << std::accumulate(elapsed_times.begin(), elapsed_times.end(),
                                     0.0) /
                         elapsed_times.size()
                  << std::endl;
    }
}
