CXXFLAGS = -std=c++11 -O3

SRC=\
Ciphertext.cpp \
Context.cpp \
EvaluatorUtils.cpp \
Key.cpp \
Numb.cpp \
Plaintext.cpp \
Scheme.cpp \
SchemeAlgo.cpp \
SecretKey.cpp \
StringUtils.cpp \
TestScheme.cpp \
TimeUtils.cpp \
main.cpp

all: $(SRC)
	$(CXX) $(CXXFLAGS) -o TestScheme $(SRC)