// This file is generated by PolyFHE
#include <cuda.h>
#include <cuda_runtime.h>
#include <chrono>
#include <iostream>
#include <numeric>
#include <vector>
#include <stdio.h>
#include "polyfhe/kernel/device_context.hpp"
#include "polyfhe/kernel/polynomial.cuh"
#include "polyfhe/kernel/ntt.hpp"
#include "polyfhe/kernel/ntt-phantom.hpp"
#include "phantom-fhe/include/phantom.h"
#include "phantom-fhe/include/uintmodmath.cuh"
// Define kernel for subgraph[0], type: Elem
__global__ void Mult_1(Params *params, uint64_t *edge_Init_0_6_Mult_1_0, uint64_t *edge_Init_0_7_Mult_1_1, uint64_t *edge_Mult_1_0_Add_2_1){
    const int start_limb = 0;
    const int end_limb = 15;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        // Mult_1
        res = xxx_multiply_and_barrett_reduce_uint64(edge_Init_0_6_Mult_1_0[n_idx] , edge_Init_0_7_Mult_1_1[n_idx], q, params->modulus_const_ratio + l_idx * 2);
         edge_Mult_1_0_Add_2_1[n_idx] = res;
    }
}


// Define kernel for subgraph[1], type: Elem
__global__ void Mult_4(Params *params, uint64_t *edge_Init_0_4_Mult_4_0, uint64_t *edge_Init_0_5_Mult_4_1, uint64_t *edge_Mult_4_0_Add_2_0){
    const int start_limb = 0;
    const int end_limb = 15;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        // Mult_4
        res = xxx_multiply_and_barrett_reduce_uint64(edge_Init_0_4_Mult_4_0[n_idx] , edge_Init_0_5_Mult_4_1[n_idx], q, params->modulus_const_ratio + l_idx * 2);
         edge_Mult_4_0_Add_2_0[n_idx] = res;
    }
}


// Define kernel for subgraph[2], type: Elem
__global__ void Add_2(Params *params, uint64_t *edge_Mult_4_0_Add_2_0, uint64_t *edge_Mult_1_0_Add_2_1, uint64_t *edge_Add_2_0_End_3_0){
    const int start_limb = 0;
    const int end_limb = 15;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        // Add_2
        res = edge_Mult_4_0_Add_2_0[n_idx] + edge_Mult_1_0_Add_2_1[n_idx];
        if (res >= q) res -= q;
        edge_Add_2_0_End_3_0[n_idx] = res;
    }
}


// Define kernel for subgraph[3], type: Elem
__global__ void Mult_5(Params *params, uint64_t *edge_Init_0_2_Mult_5_0, uint64_t *edge_Init_0_3_Mult_5_1, uint64_t *edge_Mult_5_0_End_3_1){
    const int start_limb = 0;
    const int end_limb = 15;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        // Mult_5
        res = xxx_multiply_and_barrett_reduce_uint64(edge_Init_0_2_Mult_5_0[n_idx] , edge_Init_0_3_Mult_5_1[n_idx], q, params->modulus_const_ratio + l_idx * 2);
         edge_Mult_5_0_End_3_1[n_idx] = res;
    }
}


// Define kernel for subgraph[4], type: Elem
__global__ void Mult_6(Params *params, uint64_t *edge_Init_0_0_Mult_6_0, uint64_t *edge_Init_0_1_Mult_6_1, uint64_t *edge_Mult_6_0_End_3_2, uint64_t *edge_Mult_6_1_iNTTPhase2_7_0){
    const int start_limb = 0;
    const int end_limb = 15;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        // Mult_6
        res = xxx_multiply_and_barrett_reduce_uint64(edge_Init_0_0_Mult_6_0[n_idx] , edge_Init_0_1_Mult_6_1[n_idx], q, params->modulus_const_ratio + l_idx * 2);
         edge_Mult_6_0_End_3_2[n_idx] = res;
        edge_Mult_6_1_iNTTPhase2_7_0[n_idx] = res;
    }
}


// Define kernel for subgraph[5], type: ElemLimb2
__global__ void iNTTPhase2_7(Params *params, uint64_t *edge_Mult_6_1_iNTTPhase2_7_0, uint64_t *edge_iNTTPhase2_7_0_iNTTPhase1_8_0){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 15;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // Load data to register
        const int twr_idx = tid / n_tower + start_limb;
        uint64_t *in = edge_Mult_6_1_iNTTPhase2_7_0;
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + blockIdx.x * blockDim.x * 8 + threadIdx.x * 8 + l);
        }
        __syncthreads();

        // iNTTPhase2_7
        d_poly_inwt_radix8_phase2(params, 0, shared, reg, tid);

        // Store data from register
        const size_t n_group = params->n2 / 8;
        const size_t idx_base = start_limb * params->N + blockIdx.x * blockDim.x * params->per_thread_ntt_size + (threadIdx.x / n_group) * n_group * params->per_thread_ntt_size + (threadIdx.x % n_group);
        uint64_t *out = edge_iNTTPhase2_7_0_iNTTPhase1_8_0;
        #pragma unroll
        for (int l = 0; l < 8; l++){
            *(out + idx_base + n_group * l) = reg[l];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[6], type: ElemLimb1
__global__ void iNTTPhase1_8(Params *params, uint64_t *edge_iNTTPhase2_7_0_iNTTPhase1_8_0, uint64_t *edge_iNTTPhase1_8_0_MultConst_9_0){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 15;
    uint64_t *in = edge_iNTTPhase2_7_0_iNTTPhase1_8_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // iNTTPhase1_8
        d_poly_inplace_inwt_radix8_phase1(in, params, start_limb, shared, reg, i);

        // Store data from register
        const size_t idx_out = twr_idx * params->N + n_init;
        out = edge_iNTTPhase1_8_0_MultConst_9_0;
        #pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_out + n_twr * l) = reg[l];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[7], type: Elem
__global__ void MultConst_9(Params *params, uint64_t *edge_iNTTPhase1_8_0_MultConst_9_0, uint64_t *edge_MultConst_9_0_BConv_35_0, uint64_t *edge_MultConst_9_1_BConv_32_0, uint64_t *edge_MultConst_9_2_BConv_29_0, uint64_t *edge_MultConst_9_3_BConv_26_0, uint64_t *edge_MultConst_9_4_BConv_10_0, uint64_t *modup_mult, uint64_t *modup_mult_shoup){
    const int start_limb = 0;
    const int end_limb = 15;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        res = xxx_multiply_and_reduce_shoup(edge_iNTTPhase1_8_0_MultConst_9_0[n_idx], modup_mult[l_idx], modup_mult_shoup[l_idx], q);
        edge_MultConst_9_0_BConv_35_0[n_idx] = res;
    }
}


// Define kernel for subgraph[8], type: ElemSlot
__global__ void BConv_10(Params *params, uint64_t *edge_MultConst_9_4_BConv_10_0, uint64_t *edge_BConv_10_0_NTTPhase1_11_0, const uint64_t *qiHat_mod_pj, const DModulus *ibase, uint64_t ibase_size, const DModulus *obase, uint64_t obase_size, size_t startPartIdx, size_t size_PartQl){
    extern __shared__ uint64_t shared[];
    for (size_t i = threadIdx.x; i < obase_size * ibase_size; i += blockDim.x){
        shared[i] = qiHat_mod_pj[i];
    }
    __syncthreads();
    uint64_t *out = edge_BConv_10_0_NTTPhase1_11_0;
    const int unroll_number = 2;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (params->N * obase_size + unroll_number - 1) / unroll_number; tid += blockDim.x * gridDim.x){
        const size_t n_idx = unroll_number * (tid / obase_size);
        const size_t l_idx = tid % obase_size;
        uint64_t res1, res2;
        // BConv_10
        BConvOpNoReg(params, &res1, &res2, edge_MultConst_9_4_BConv_10_0 + params->N * startPartIdx, shared, n_idx, l_idx, ibase, ibase_size, obase, obase_size, startPartIdx, size_PartQl);
        const size_t l_out_idx = l_idx + ((l_idx >= startPartIdx) ? size_PartQl : 0);
        asm("st.cs.global.v2.u64 [%0], {%1, %2};":: "l"(out + l_out_idx * params->N + n_idx),"l"(res1), "l"(res2));
    }
}


// Define kernel for subgraph[9], type: ElemLimb1
__global__ void NTTPhase1_11(Params *params, uint64_t *edge_BConv_10_0_NTTPhase1_11_0, uint64_t *edge_NTTPhase1_11_0_NTTPhase2_12_0, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    uint64_t *in = edge_BConv_10_0_NTTPhase1_11_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // NTTPhase1_11
        const size_t exclude_start = 12;
        const size_t exclude_end = 15;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){
            continue;
        }

        // Load to register
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + twr_idx * params->N + n_init + n_twr * l);
        }
        out = edge_NTTPhase1_11_0_NTTPhase2_12_0;
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 = (twr_idx >= start_limb + end_limb - size_P ? size_QP - (start_limb + end_limb - twr_idx) : twr_idx);
        d_poly_fnwt_phase1(params, out, shared, reg, twiddles, twiddles_shoup, modulus, twr_idx, twr_idx2, n_init, i);
    }
}


// Define kernel for subgraph[10], type: ElemLimb2
__global__ void NTTPhase2_12(Params *params, uint64_t *edge_NTTPhase1_11_0_NTTPhase2_12_0, uint64_t *edge_NTTPhase2_12_0_MultKeyAccum_13_4, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // NTTPhase2_12
        size_t twr_idx = end_limb - 1 - (tid / n_tower) + start_limb;
        const size_t exclude_end = 15;
        const size_t exclude_start = 12;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){continue;}
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 =(twr_idx >= start_limb + end_limb - size_P? size_QP - (start_limb + end_limb - twr_idx): twr_idx);
        uint64_t n_init;
        d_poly_fnwt_phase2(params, edge_NTTPhase1_11_0_NTTPhase2_12_0, shared, reg, twiddles,twiddles_shoup, modulus, end_limb,start_limb, twr_idx, twr_idx2, &n_init, tid);
        uint64_t *out_ptr = edge_NTTPhase2_12_0_MultKeyAccum_13_4 + twr_idx * params->N;
        #pragma unroll
        for (size_t j = 0; j < 8; j++){
            *(out_ptr + n_init + params->n2 / 8 * j) = reg[j];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[11], type: ElemSlot
__global__ void BConv_26(Params *params, uint64_t *edge_MultConst_9_3_BConv_26_0, uint64_t *edge_BConv_26_0_NTTPhase1_27_0, const uint64_t *qiHat_mod_pj, const DModulus *ibase, uint64_t ibase_size, const DModulus *obase, uint64_t obase_size, size_t startPartIdx, size_t size_PartQl){
    extern __shared__ uint64_t shared[];
    for (size_t i = threadIdx.x; i < obase_size * ibase_size; i += blockDim.x){
        shared[i] = qiHat_mod_pj[i];
    }
    __syncthreads();
    uint64_t *out = edge_BConv_26_0_NTTPhase1_27_0;
    const int unroll_number = 2;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (params->N * obase_size + unroll_number - 1) / unroll_number; tid += blockDim.x * gridDim.x){
        const size_t n_idx = unroll_number * (tid / obase_size);
        const size_t l_idx = tid % obase_size;
        uint64_t res1, res2;
        // BConv_26
        BConvOpNoReg(params, &res1, &res2, edge_MultConst_9_3_BConv_26_0 + params->N * startPartIdx, shared, n_idx, l_idx, ibase, ibase_size, obase, obase_size, startPartIdx, size_PartQl);
        const size_t l_out_idx = l_idx + ((l_idx >= startPartIdx) ? size_PartQl : 0);
        asm("st.cs.global.v2.u64 [%0], {%1, %2};":: "l"(out + l_out_idx * params->N + n_idx),"l"(res1), "l"(res2));
    }
}


// Define kernel for subgraph[12], type: ElemLimb1
__global__ void NTTPhase1_27(Params *params, uint64_t *edge_BConv_26_0_NTTPhase1_27_0, uint64_t *edge_NTTPhase1_27_0_NTTPhase2_28_0, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    uint64_t *in = edge_BConv_26_0_NTTPhase1_27_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // NTTPhase1_27
        const size_t exclude_start = 9;
        const size_t exclude_end = 12;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){
            continue;
        }

        // Load to register
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + twr_idx * params->N + n_init + n_twr * l);
        }
        out = edge_NTTPhase1_27_0_NTTPhase2_28_0;
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 = (twr_idx >= start_limb + end_limb - size_P ? size_QP - (start_limb + end_limb - twr_idx) : twr_idx);
        d_poly_fnwt_phase1(params, out, shared, reg, twiddles, twiddles_shoup, modulus, twr_idx, twr_idx2, n_init, i);
    }
}


// Define kernel for subgraph[13], type: ElemLimb2
__global__ void NTTPhase2_28(Params *params, uint64_t *edge_NTTPhase1_27_0_NTTPhase2_28_0, uint64_t *edge_NTTPhase2_28_0_MultKeyAccum_13_3, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // NTTPhase2_28
        size_t twr_idx = end_limb - 1 - (tid / n_tower) + start_limb;
        const size_t exclude_end = 12;
        const size_t exclude_start = 9;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){continue;}
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 =(twr_idx >= start_limb + end_limb - size_P? size_QP - (start_limb + end_limb - twr_idx): twr_idx);
        uint64_t n_init;
        d_poly_fnwt_phase2(params, edge_NTTPhase1_27_0_NTTPhase2_28_0, shared, reg, twiddles,twiddles_shoup, modulus, end_limb,start_limb, twr_idx, twr_idx2, &n_init, tid);
        uint64_t *out_ptr = edge_NTTPhase2_28_0_MultKeyAccum_13_3 + twr_idx * params->N;
        #pragma unroll
        for (size_t j = 0; j < 8; j++){
            *(out_ptr + n_init + params->n2 / 8 * j) = reg[j];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[14], type: ElemSlot
__global__ void BConv_29(Params *params, uint64_t *edge_MultConst_9_2_BConv_29_0, uint64_t *edge_BConv_29_0_NTTPhase1_30_0, const uint64_t *qiHat_mod_pj, const DModulus *ibase, uint64_t ibase_size, const DModulus *obase, uint64_t obase_size, size_t startPartIdx, size_t size_PartQl){
    extern __shared__ uint64_t shared[];
    for (size_t i = threadIdx.x; i < obase_size * ibase_size; i += blockDim.x){
        shared[i] = qiHat_mod_pj[i];
    }
    __syncthreads();
    uint64_t *out = edge_BConv_29_0_NTTPhase1_30_0;
    const int unroll_number = 2;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (params->N * obase_size + unroll_number - 1) / unroll_number; tid += blockDim.x * gridDim.x){
        const size_t n_idx = unroll_number * (tid / obase_size);
        const size_t l_idx = tid % obase_size;
        uint64_t res1, res2;
        // BConv_29
        BConvOpNoReg(params, &res1, &res2, edge_MultConst_9_2_BConv_29_0 + params->N * startPartIdx, shared, n_idx, l_idx, ibase, ibase_size, obase, obase_size, startPartIdx, size_PartQl);
        const size_t l_out_idx = l_idx + ((l_idx >= startPartIdx) ? size_PartQl : 0);
        asm("st.cs.global.v2.u64 [%0], {%1, %2};":: "l"(out + l_out_idx * params->N + n_idx),"l"(res1), "l"(res2));
    }
}


// Define kernel for subgraph[15], type: ElemLimb1
__global__ void NTTPhase1_30(Params *params, uint64_t *edge_BConv_29_0_NTTPhase1_30_0, uint64_t *edge_NTTPhase1_30_0_NTTPhase2_31_0, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    uint64_t *in = edge_BConv_29_0_NTTPhase1_30_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // NTTPhase1_30
        const size_t exclude_start = 6;
        const size_t exclude_end = 9;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){
            continue;
        }

        // Load to register
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + twr_idx * params->N + n_init + n_twr * l);
        }
        out = edge_NTTPhase1_30_0_NTTPhase2_31_0;
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 = (twr_idx >= start_limb + end_limb - size_P ? size_QP - (start_limb + end_limb - twr_idx) : twr_idx);
        d_poly_fnwt_phase1(params, out, shared, reg, twiddles, twiddles_shoup, modulus, twr_idx, twr_idx2, n_init, i);
    }
}


// Define kernel for subgraph[16], type: ElemLimb2
__global__ void NTTPhase2_31(Params *params, uint64_t *edge_NTTPhase1_30_0_NTTPhase2_31_0, uint64_t *edge_NTTPhase2_31_0_MultKeyAccum_13_2, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // NTTPhase2_31
        size_t twr_idx = end_limb - 1 - (tid / n_tower) + start_limb;
        const size_t exclude_end = 9;
        const size_t exclude_start = 6;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){continue;}
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 =(twr_idx >= start_limb + end_limb - size_P? size_QP - (start_limb + end_limb - twr_idx): twr_idx);
        uint64_t n_init;
        d_poly_fnwt_phase2(params, edge_NTTPhase1_30_0_NTTPhase2_31_0, shared, reg, twiddles,twiddles_shoup, modulus, end_limb,start_limb, twr_idx, twr_idx2, &n_init, tid);
        uint64_t *out_ptr = edge_NTTPhase2_31_0_MultKeyAccum_13_2 + twr_idx * params->N;
        #pragma unroll
        for (size_t j = 0; j < 8; j++){
            *(out_ptr + n_init + params->n2 / 8 * j) = reg[j];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[17], type: ElemSlot
__global__ void BConv_32(Params *params, uint64_t *edge_MultConst_9_1_BConv_32_0, uint64_t *edge_BConv_32_0_NTTPhase1_33_0, const uint64_t *qiHat_mod_pj, const DModulus *ibase, uint64_t ibase_size, const DModulus *obase, uint64_t obase_size, size_t startPartIdx, size_t size_PartQl){
    extern __shared__ uint64_t shared[];
    for (size_t i = threadIdx.x; i < obase_size * ibase_size; i += blockDim.x){
        shared[i] = qiHat_mod_pj[i];
    }
    __syncthreads();
    uint64_t *out = edge_BConv_32_0_NTTPhase1_33_0;
    const int unroll_number = 2;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (params->N * obase_size + unroll_number - 1) / unroll_number; tid += blockDim.x * gridDim.x){
        const size_t n_idx = unroll_number * (tid / obase_size);
        const size_t l_idx = tid % obase_size;
        uint64_t res1, res2;
        // BConv_32
        BConvOpNoReg(params, &res1, &res2, edge_MultConst_9_1_BConv_32_0 + params->N * startPartIdx, shared, n_idx, l_idx, ibase, ibase_size, obase, obase_size, startPartIdx, size_PartQl);
        const size_t l_out_idx = l_idx + ((l_idx >= startPartIdx) ? size_PartQl : 0);
        asm("st.cs.global.v2.u64 [%0], {%1, %2};":: "l"(out + l_out_idx * params->N + n_idx),"l"(res1), "l"(res2));
    }
}


// Define kernel for subgraph[18], type: ElemLimb1
__global__ void NTTPhase1_33(Params *params, uint64_t *edge_BConv_32_0_NTTPhase1_33_0, uint64_t *edge_NTTPhase1_33_0_NTTPhase2_34_0, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    uint64_t *in = edge_BConv_32_0_NTTPhase1_33_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // NTTPhase1_33
        const size_t exclude_start = 3;
        const size_t exclude_end = 6;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){
            continue;
        }

        // Load to register
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + twr_idx * params->N + n_init + n_twr * l);
        }
        out = edge_NTTPhase1_33_0_NTTPhase2_34_0;
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 = (twr_idx >= start_limb + end_limb - size_P ? size_QP - (start_limb + end_limb - twr_idx) : twr_idx);
        d_poly_fnwt_phase1(params, out, shared, reg, twiddles, twiddles_shoup, modulus, twr_idx, twr_idx2, n_init, i);
    }
}


// Define kernel for subgraph[19], type: ElemLimb2
__global__ void NTTPhase2_34(Params *params, uint64_t *edge_NTTPhase1_33_0_NTTPhase2_34_0, uint64_t *edge_NTTPhase2_34_0_MultKeyAccum_13_1, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // NTTPhase2_34
        size_t twr_idx = end_limb - 1 - (tid / n_tower) + start_limb;
        const size_t exclude_end = 6;
        const size_t exclude_start = 3;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){continue;}
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 =(twr_idx >= start_limb + end_limb - size_P? size_QP - (start_limb + end_limb - twr_idx): twr_idx);
        uint64_t n_init;
        d_poly_fnwt_phase2(params, edge_NTTPhase1_33_0_NTTPhase2_34_0, shared, reg, twiddles,twiddles_shoup, modulus, end_limb,start_limb, twr_idx, twr_idx2, &n_init, tid);
        uint64_t *out_ptr = edge_NTTPhase2_34_0_MultKeyAccum_13_1 + twr_idx * params->N;
        #pragma unroll
        for (size_t j = 0; j < 8; j++){
            *(out_ptr + n_init + params->n2 / 8 * j) = reg[j];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[20], type: ElemSlot
__global__ void BConv_35(Params *params, uint64_t *edge_MultConst_9_0_BConv_35_0, uint64_t *edge_BConv_35_0_NTTPhase1_36_0, const uint64_t *qiHat_mod_pj, const DModulus *ibase, uint64_t ibase_size, const DModulus *obase, uint64_t obase_size, size_t startPartIdx, size_t size_PartQl){
    extern __shared__ uint64_t shared[];
    for (size_t i = threadIdx.x; i < obase_size * ibase_size; i += blockDim.x){
        shared[i] = qiHat_mod_pj[i];
    }
    __syncthreads();
    uint64_t *out = edge_BConv_35_0_NTTPhase1_36_0;
    const int unroll_number = 2;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (params->N * obase_size + unroll_number - 1) / unroll_number; tid += blockDim.x * gridDim.x){
        const size_t n_idx = unroll_number * (tid / obase_size);
        const size_t l_idx = tid % obase_size;
        uint64_t res1, res2;
        // BConv_35
        BConvOpNoReg(params, &res1, &res2, edge_MultConst_9_0_BConv_35_0 + params->N * startPartIdx, shared, n_idx, l_idx, ibase, ibase_size, obase, obase_size, startPartIdx, size_PartQl);
        const size_t l_out_idx = l_idx + ((l_idx >= startPartIdx) ? size_PartQl : 0);
        asm("st.cs.global.v2.u64 [%0], {%1, %2};":: "l"(out + l_out_idx * params->N + n_idx),"l"(res1), "l"(res2));
    }
}


// Define kernel for subgraph[21], type: ElemLimb1
__global__ void NTTPhase1_36(Params *params, uint64_t *edge_BConv_35_0_NTTPhase1_36_0, uint64_t *edge_NTTPhase1_36_0_NTTPhase2_37_0, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    uint64_t *in = edge_BConv_35_0_NTTPhase1_36_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // NTTPhase1_36
        const size_t exclude_start = 0;
        const size_t exclude_end = 3;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){
            continue;
        }

        // Load to register
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + twr_idx * params->N + n_init + n_twr * l);
        }
        out = edge_NTTPhase1_36_0_NTTPhase2_37_0;
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 = (twr_idx >= start_limb + end_limb - size_P ? size_QP - (start_limb + end_limb - twr_idx) : twr_idx);
        d_poly_fnwt_phase1(params, out, shared, reg, twiddles, twiddles_shoup, modulus, twr_idx, twr_idx2, n_init, i);
    }
}


// Define kernel for subgraph[22], type: ElemLimb2
__global__ void NTTPhase2_37(Params *params, uint64_t *edge_NTTPhase1_36_0_NTTPhase2_37_0, uint64_t *edge_NTTPhase2_37_0_MultKeyAccum_13_0, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 18;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // NTTPhase2_37
        size_t twr_idx = end_limb - 1 - (tid / n_tower) + start_limb;
        const size_t exclude_end = 3;
        const size_t exclude_start = 0;
        if (twr_idx >= exclude_start && twr_idx < exclude_end){continue;}
        const uint64_t size_P = params->K;
        const uint64_t size_QP = params->KL;
        size_t twr_idx2 =(twr_idx >= start_limb + end_limb - size_P? size_QP - (start_limb + end_limb - twr_idx): twr_idx);
        uint64_t n_init;
        d_poly_fnwt_phase2(params, edge_NTTPhase1_36_0_NTTPhase2_37_0, shared, reg, twiddles,twiddles_shoup, modulus, end_limb,start_limb, twr_idx, twr_idx2, &n_init, tid);
        uint64_t *out_ptr = edge_NTTPhase2_37_0_MultKeyAccum_13_0 + twr_idx * params->N;
        #pragma unroll
        for (size_t j = 0; j < 8; j++){
            *(out_ptr + n_init + params->n2 / 8 * j) = reg[j];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[23], type: Elem
__global__ void MultKeyAccum_13(Params *params, uint64_t *edge_NTTPhase2_37_0_MultKeyAccum_13_0, uint64_t *edge_NTTPhase2_34_0_MultKeyAccum_13_1, uint64_t *edge_NTTPhase2_31_0_MultKeyAccum_13_2, uint64_t *edge_NTTPhase2_28_0_MultKeyAccum_13_3, uint64_t *edge_NTTPhase2_12_0_MultKeyAccum_13_4, uint64_t *edge_MultKeyAccum_13_0_iNTTPhase2_20_0, uint64_t *edge_MultKeyAccum_13_1_iNTTPhase2_14_0, uint64_t **relin_keys){
    const int start_limb = 0;
    const int end_limb = 18;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        // MultKeyAccum_13
        uint64_t *in_list[5] = {edge_NTTPhase2_37_0_MultKeyAccum_13_0, edge_NTTPhase2_34_0_MultKeyAccum_13_1, edge_NTTPhase2_31_0_MultKeyAccum_13_2, edge_NTTPhase2_28_0_MultKeyAccum_13_3, edge_NTTPhase2_12_0_MultKeyAccum_13_4};
        MulKeyAccumOp(params,edge_MultKeyAccum_13_0_iNTTPhase2_20_0, edge_MultKeyAccum_13_1_iNTTPhase2_14_0, in_list, relin_keys, 5, idx, l_idx);
    }
}


// Define kernel for subgraph[24], type: ElemLimb2
__global__ void iNTTPhase2_14(Params *params, uint64_t *edge_MultKeyAccum_13_1_iNTTPhase2_14_0, uint64_t *edge_iNTTPhase2_14_0_iNTTPhase1_15_0){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 15;
    const int end_limb = 18;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // Load data to register
        const int twr_idx = tid / n_tower + start_limb;
        uint64_t *in = edge_MultKeyAccum_13_1_iNTTPhase2_14_0;
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + blockIdx.x * blockDim.x * 8 + threadIdx.x * 8 + l);
        }
        __syncthreads();

        // iNTTPhase2_14
        d_poly_inwt_radix8_phase2(params, 15, shared, reg, tid);

        // Store data from register
        const size_t n_group = params->n2 / 8;
        const size_t idx_base = start_limb * params->N + blockIdx.x * blockDim.x * params->per_thread_ntt_size + (threadIdx.x / n_group) * n_group * params->per_thread_ntt_size + (threadIdx.x % n_group);
        uint64_t *out = edge_iNTTPhase2_14_0_iNTTPhase1_15_0;
        #pragma unroll
        for (int l = 0; l < 8; l++){
            *(out + idx_base + n_group * l) = reg[l];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[25], type: ElemLimb1
__global__ void iNTTPhase1_15(Params *params, uint64_t *edge_iNTTPhase2_14_0_iNTTPhase1_15_0, uint64_t *edge_iNTTPhase1_15_0_MultConst_16_0){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 15;
    const int end_limb = 18;
    uint64_t *in = edge_iNTTPhase2_14_0_iNTTPhase1_15_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // iNTTPhase1_15
        d_poly_inplace_inwt_radix8_phase1(in, params, start_limb, shared, reg, i);

        // Store data from register
        const size_t idx_out = twr_idx * params->N + n_init;
        out = edge_iNTTPhase1_15_0_MultConst_16_0;
        #pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_out + n_twr * l) = reg[l];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[26], type: Elem
__global__ void MultConst_16(Params *params, uint64_t *edge_iNTTPhase1_15_0_MultConst_16_0, uint64_t *edge_MultConst_16_0_Unknown_17_0, uint64_t *moddown_mult, uint64_t *moddown_mult_shoup){
    const int start_limb = 0;
    const int end_limb = 3;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        res = xxx_multiply_and_reduce_shoup(edge_iNTTPhase1_15_0_MultConst_16_0[n_idx], moddown_mult[l_idx - start_limb], moddown_mult_shoup[l_idx - start_limb], q);
        edge_MultConst_16_0_Unknown_17_0[n_idx] = res;
    }
}


// Define kernel for subgraph[28], type: ElemLimb1
__global__ void NTTPhase1_18(Params *params, uint64_t *edge_Unknown_17_0_NTTPhase1_18_0, uint64_t *edge_NTTPhase1_18_0_NTTPhase2_19_0, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 15;
    uint64_t *in = edge_Unknown_17_0_NTTPhase1_18_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // NTTPhase1_18

        // Load to register
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + twr_idx * params->N + n_init + n_twr * l);
        }
        out = edge_NTTPhase1_18_0_NTTPhase2_19_0;
        d_poly_fnwt_phase1(params, out, shared, reg, twiddles, twiddles_shoup, modulus, twr_idx, twr_idx, n_init, i);
    }
}


// Define kernel for subgraph[29], type: ElemLimb2
__global__ void NTTPhase2_19(Params *params, uint64_t *edge_NTTPhase1_18_0_NTTPhase2_19_0, uint64_t *edge_NTTPhase2_19_0_End_3_4, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 15;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // NTTPhase2_19
        size_t twr_idx = end_limb - 1 - (tid / n_tower) + start_limb;
        uint64_t n_init;
        d_poly_fnwt_phase2(params, edge_NTTPhase1_18_0_NTTPhase2_19_0, shared, reg, twiddles,twiddles_shoup, modulus, end_limb,start_limb, twr_idx, twr_idx, &n_init, tid);
        uint64_t *out_ptr = edge_NTTPhase2_19_0_End_3_4 + twr_idx * params->N;
        #pragma unroll
        for (size_t j = 0; j < 8; j++){
            *(out_ptr + n_init + params->n2 / 8 * j) = reg[j];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[30], type: ElemLimb2
__global__ void iNTTPhase2_20(Params *params, uint64_t *edge_MultKeyAccum_13_0_iNTTPhase2_20_0, uint64_t *edge_iNTTPhase2_20_0_iNTTPhase1_21_0){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 15;
    const int end_limb = 18;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // Load data to register
        const int twr_idx = tid / n_tower + start_limb;
        uint64_t *in = edge_MultKeyAccum_13_0_iNTTPhase2_20_0;
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + blockIdx.x * blockDim.x * 8 + threadIdx.x * 8 + l);
        }
        __syncthreads();

        // iNTTPhase2_20
        d_poly_inwt_radix8_phase2(params, 15, shared, reg, tid);

        // Store data from register
        const size_t n_group = params->n2 / 8;
        const size_t idx_base = start_limb * params->N + blockIdx.x * blockDim.x * params->per_thread_ntt_size + (threadIdx.x / n_group) * n_group * params->per_thread_ntt_size + (threadIdx.x % n_group);
        uint64_t *out = edge_iNTTPhase2_20_0_iNTTPhase1_21_0;
        #pragma unroll
        for (int l = 0; l < 8; l++){
            *(out + idx_base + n_group * l) = reg[l];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[31], type: ElemLimb1
__global__ void iNTTPhase1_21(Params *params, uint64_t *edge_iNTTPhase2_20_0_iNTTPhase1_21_0, uint64_t *edge_iNTTPhase1_21_0_MultConst_22_0){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 15;
    const int end_limb = 18;
    uint64_t *in = edge_iNTTPhase2_20_0_iNTTPhase1_21_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // iNTTPhase1_21
        d_poly_inplace_inwt_radix8_phase1(in, params, start_limb, shared, reg, i);

        // Store data from register
        const size_t idx_out = twr_idx * params->N + n_init;
        out = edge_iNTTPhase1_21_0_MultConst_22_0;
        #pragma unroll
        for (int l = 0; l < 8; l++) {
            *(out + idx_out + n_twr * l) = reg[l];
        }
        __syncthreads();
    }
}


// Define kernel for subgraph[32], type: Elem
__global__ void MultConst_22(Params *params, uint64_t *edge_iNTTPhase1_21_0_MultConst_22_0, uint64_t *edge_MultConst_22_0_Unknown_23_0, uint64_t *moddown_mult, uint64_t *moddown_mult_shoup){
    const int start_limb = 0;
    const int end_limb = 3;
    for (int idx = threadIdx.x + blockIdx.x * blockDim.x;idx < params->N * (end_limb - start_limb);idx += blockDim.x * gridDim.x){
        const int l_idx = idx / params->N + start_limb;
        const uint64_t q = params->qVec[l_idx];
        uint64_t res;
        const int n_idx = l_idx * params->N + idx % params->N;
        res = xxx_multiply_and_reduce_shoup(edge_iNTTPhase1_21_0_MultConst_22_0[n_idx], moddown_mult[l_idx - start_limb], moddown_mult_shoup[l_idx - start_limb], q);
        edge_MultConst_22_0_Unknown_23_0[n_idx] = res;
    }
}


// Define kernel for subgraph[34], type: ElemLimb1
__global__ void NTTPhase1_24(Params *params, uint64_t *edge_Unknown_23_0_NTTPhase1_24_0, uint64_t *edge_NTTPhase1_24_0_NTTPhase2_25_0, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 15;
    uint64_t *in = edge_Unknown_23_0_NTTPhase1_24_0;
    for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < (params->N / 8 * (end_limb - start_limb)); i += blockDim.x * gridDim.x){
        const size_t n_twr = params->N / 8;
        const size_t n_idx = i % n_twr;
        const size_t twr_idx = i / n_twr + start_limb;
        const size_t group = params->n1 / 8;
        const size_t pad_tid = threadIdx.x % params->pad;
        const size_t pad_idx = threadIdx.x / params->pad;
        const size_t n_init = n_twr / group * pad_idx + pad_tid + params->pad * (n_idx / (group * params->pad));
        uint64_t *out;
        // NTTPhase1_24

        // Load to register
        #pragma unroll
        for (int l = 0; l < 8; l++){
            reg[l] = *(in + twr_idx * params->N + n_init + n_twr * l);
        }
        out = edge_NTTPhase1_24_0_NTTPhase2_25_0;
        d_poly_fnwt_phase1(params, out, shared, reg, twiddles, twiddles_shoup, modulus, twr_idx, twr_idx, n_init, i);
    }
}


// Define kernel for subgraph[35], type: ElemLimb2
__global__ void NTTPhase2_25(Params *params, uint64_t *edge_NTTPhase1_24_0_NTTPhase2_25_0, uint64_t *edge_NTTPhase2_25_0_End_3_3, const uint64_t *twiddles, const uint64_t *twiddles_shoup, const DModulus *modulus){
    extern __shared__ uint64_t shared[];
    uint64_t reg[8];
    const int start_limb = 0;
    const int end_limb = 15;
    const size_t n_tower = params->N / 8;
    for (size_t tid = blockIdx.x * blockDim.x + threadIdx.x; tid < (end_limb - start_limb) * n_tower; tid += blockDim.x * gridDim.x){

        // NTTPhase2_25
        size_t twr_idx = end_limb - 1 - (tid / n_tower) + start_limb;
        uint64_t n_init;
        d_poly_fnwt_phase2(params, edge_NTTPhase1_24_0_NTTPhase2_25_0, shared, reg, twiddles,twiddles_shoup, modulus, end_limb,start_limb, twr_idx, twr_idx, &n_init, tid);
        uint64_t *out_ptr = edge_NTTPhase2_25_0_End_3_3 + twr_idx * params->N;
        #pragma unroll
        for (size_t j = 0; j < 8; j++){
            *(out_ptr + n_init + params->n2 / 8 * j) = reg[j];
        }
        __syncthreads();
    }
}


void entry_kernel(Params *params_d, Params *params_h, PhantomContext &context, uint64_t **relin_keys, uint64_t *in0, uint64_t *in1, uint64_t *out0, uint64_t *out1, bool if_benchmark, int n_opt){
    phantom::DRNSTool *rns_tool = params_h->rns_tools[1];

    // =====================================
    // Input arguments
    // =====================================
    // Edge: Init_0 -> Mult_6
    uint64_t *edge_Init_0_0_Mult_6_0_d = in0 + 491520;
    // Edge: Init_0 -> Mult_6
    uint64_t *edge_Init_0_1_Mult_6_1_d = in1 + 491520;
    // Edge: Init_0 -> Mult_5
    uint64_t *edge_Init_0_2_Mult_5_0_d = in0 + 0;
    // Edge: Init_0 -> Mult_5
    uint64_t *edge_Init_0_3_Mult_5_1_d = in1 + 0;
    // Edge: Init_0 -> Mult_4
    uint64_t *edge_Init_0_4_Mult_4_0_d = in0 + 0;
    // Edge: Init_0 -> Mult_4
    uint64_t *edge_Init_0_5_Mult_4_1_d = in1 + 491520;
    // Edge: Init_0 -> Mult_1
    uint64_t *edge_Init_0_6_Mult_1_0_d = in0 + 491520;
    // Edge: Init_0 -> Mult_1
    uint64_t *edge_Init_0_7_Mult_1_1_d = in1 + 0;

    // =====================================
    // Output arguments
    // =====================================
    // Edge: Add_2 -> End_3
    uint64_t *edge_Add_2_0_End_3_0_d = out0 + 491520;
    // Edge: Mult_5 -> End_3
    uint64_t *edge_Mult_5_0_End_3_1_d = out0 + 0;
    // Edge: Mult_6 -> End_3
    uint64_t *edge_Mult_6_0_End_3_2_d = out0 + 983040;
    // Edge: NTTPhase2_25 -> End_3
    uint64_t *edge_NTTPhase2_25_0_End_3_3_d = out1 + 0;
    // Edge: NTTPhase2_19 -> End_3
    uint64_t *edge_NTTPhase2_19_0_End_3_4_d = out1 + 589824;

    // =====================================
    // Edges
    // Define global edges for GPU
    // =====================================
    // Edge: Mult_1 -> Add_2
    uint64_t *edge_Mult_1_0_Add_2_1_d;
    checkCudaErrors(cudaMalloc((void**)&edge_Mult_1_0_Add_2_1_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: Mult_4 -> Add_2
    uint64_t *edge_Mult_4_0_Add_2_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_Mult_4_0_Add_2_0_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: Mult_6 -> iNTTPhase2_7
    uint64_t *edge_Mult_6_1_iNTTPhase2_7_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_Mult_6_1_iNTTPhase2_7_0_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: iNTTPhase2_7 -> iNTTPhase1_8
    uint64_t *edge_iNTTPhase2_7_0_iNTTPhase1_8_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_iNTTPhase2_7_0_iNTTPhase1_8_0_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: iNTTPhase1_8 -> MultConst_9
    uint64_t *edge_iNTTPhase1_8_0_MultConst_9_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_iNTTPhase1_8_0_MultConst_9_0_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: MultConst_9 -> BConv_35
    uint64_t *edge_MultConst_9_0_BConv_35_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_MultConst_9_0_BConv_35_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: BConv_10 -> NTTPhase1_11
    uint64_t *edge_BConv_10_0_NTTPhase1_11_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_BConv_10_0_NTTPhase1_11_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase1_11 -> NTTPhase2_12
    uint64_t *edge_NTTPhase1_11_0_NTTPhase2_12_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase1_11_0_NTTPhase2_12_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_12 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_12_0_MultKeyAccum_13_4_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase2_12_0_MultKeyAccum_13_4_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: BConv_26 -> NTTPhase1_27
    uint64_t *edge_BConv_26_0_NTTPhase1_27_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_BConv_26_0_NTTPhase1_27_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase1_27 -> NTTPhase2_28
    uint64_t *edge_NTTPhase1_27_0_NTTPhase2_28_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase1_27_0_NTTPhase2_28_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_28 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_28_0_MultKeyAccum_13_3_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase2_28_0_MultKeyAccum_13_3_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: BConv_29 -> NTTPhase1_30
    uint64_t *edge_BConv_29_0_NTTPhase1_30_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_BConv_29_0_NTTPhase1_30_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase1_30 -> NTTPhase2_31
    uint64_t *edge_NTTPhase1_30_0_NTTPhase2_31_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase1_30_0_NTTPhase2_31_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_31 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_31_0_MultKeyAccum_13_2_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase2_31_0_MultKeyAccum_13_2_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: BConv_32 -> NTTPhase1_33
    uint64_t *edge_BConv_32_0_NTTPhase1_33_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_BConv_32_0_NTTPhase1_33_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase1_33 -> NTTPhase2_34
    uint64_t *edge_NTTPhase1_33_0_NTTPhase2_34_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase1_33_0_NTTPhase2_34_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_34 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_34_0_MultKeyAccum_13_1_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase2_34_0_MultKeyAccum_13_1_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: BConv_35 -> NTTPhase1_36
    uint64_t *edge_BConv_35_0_NTTPhase1_36_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_BConv_35_0_NTTPhase1_36_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase1_36 -> NTTPhase2_37
    uint64_t *edge_NTTPhase1_36_0_NTTPhase2_37_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase1_36_0_NTTPhase2_37_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase2_37 -> MultKeyAccum_13
    uint64_t *edge_NTTPhase2_37_0_MultKeyAccum_13_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase2_37_0_MultKeyAccum_13_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: MultKeyAccum_13 -> iNTTPhase2_20
    uint64_t *edge_MultKeyAccum_13_0_iNTTPhase2_20_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_MultKeyAccum_13_0_iNTTPhase2_20_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: MultKeyAccum_13 -> iNTTPhase2_14
    uint64_t *edge_MultKeyAccum_13_1_iNTTPhase2_14_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_MultKeyAccum_13_1_iNTTPhase2_14_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: iNTTPhase2_14 -> iNTTPhase1_15
    uint64_t *edge_iNTTPhase2_14_0_iNTTPhase1_15_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_iNTTPhase2_14_0_iNTTPhase1_15_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: iNTTPhase1_15 -> MultConst_16
    uint64_t *edge_iNTTPhase1_15_0_MultConst_16_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_iNTTPhase1_15_0_MultConst_16_0_d, 3 * params_h->N * sizeof(uint64_t)));
    // Edge: MultConst_16 -> Unknown_17
    uint64_t *edge_MultConst_16_0_Unknown_17_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_MultConst_16_0_Unknown_17_0_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: Unknown_17 -> NTTPhase1_18
    uint64_t *edge_Unknown_17_0_NTTPhase1_18_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_Unknown_17_0_NTTPhase1_18_0_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase1_18 -> NTTPhase2_19
    uint64_t *edge_NTTPhase1_18_0_NTTPhase2_19_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase1_18_0_NTTPhase2_19_0_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: iNTTPhase2_20 -> iNTTPhase1_21
    uint64_t *edge_iNTTPhase2_20_0_iNTTPhase1_21_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_iNTTPhase2_20_0_iNTTPhase1_21_0_d, 18 * params_h->N * sizeof(uint64_t)));
    // Edge: iNTTPhase1_21 -> MultConst_22
    uint64_t *edge_iNTTPhase1_21_0_MultConst_22_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_iNTTPhase1_21_0_MultConst_22_0_d, 3 * params_h->N * sizeof(uint64_t)));
    // Edge: MultConst_22 -> Unknown_23
    uint64_t *edge_MultConst_22_0_Unknown_23_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_MultConst_22_0_Unknown_23_0_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: Unknown_23 -> NTTPhase1_24
    uint64_t *edge_Unknown_23_0_NTTPhase1_24_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_Unknown_23_0_NTTPhase1_24_0_d, 15 * params_h->N * sizeof(uint64_t)));
    // Edge: NTTPhase1_24 -> NTTPhase2_25
    uint64_t *edge_NTTPhase1_24_0_NTTPhase2_25_0_d;
    checkCudaErrors(cudaMalloc((void**)&edge_NTTPhase1_24_0_NTTPhase2_25_0_d, 15 * params_h->N * sizeof(uint64_t)));
    uint64_t *edge_MultConst_9_1_BConv_32_0_d = edge_MultConst_9_0_BConv_35_0_d;
    uint64_t *edge_MultConst_9_2_BConv_29_0_d = edge_MultConst_9_0_BConv_35_0_d;
    uint64_t *edge_MultConst_9_3_BConv_26_0_d = edge_MultConst_9_0_BConv_35_0_d;
    uint64_t *edge_MultConst_9_4_BConv_10_0_d = edge_MultConst_9_0_BConv_35_0_d;
    // =====================================
    std::cout << "### Warm up and Test" << std::endl;
    std::cout << "N : " << params_h->N << std::endl;
    std::cout << "L : " << params_h->L << std::endl;
    std::cout << "dnum : " << params_h->dnum << std::endl;
    std::cout << "K : " << params_h->K << std::endl;
    std::cout << "KL : " << params_h->KL << std::endl;
    std::cout << "alpha : " << params_h->alpha << std::endl;
    phantom::DRNSTool *drns_tool = params_h->rns_tools[1];
    const int beta = std::ceil(1.0 * params_h->L / params_h->alpha);
    std::cout << "beta: " << beta << std::endl;
    // ModUp
    uint64_t *modup_mult = rns_tool->partQlHatInv_mod_Ql_concat();
    uint64_t *modup_mult_shoup = rns_tool->partQlHatInv_mod_Ql_concat_shoup();
    // ModDown
    const DBaseConverter moddown_converter = drns_tool->base_P_to_Ql_conv();
    uint64_t *moddown_mult = moddown_converter.ibase().QHatInvModq();
    uint64_t *moddown_mult_shoup = moddown_converter.ibase().QHatInvModq_shoup();
    uint64_t *moddown_matmul = moddown_converter.QHatModp();
    // qHatModp
    uint64_t **qhat_modp_list = new uint64_t *[beta];
    for (int j = 0; j < beta; j++) {
    qhat_modp_list[j] = drns_tool->v_base_part_Ql_to_compl_part_QlP_conv()[j].QHatModp();
    }
    uint64_t** d_qhat_modp_list;
    checkCudaErrors(cudaMalloc((void**) &d_qhat_modp_list, sizeof(uint64_t*) * beta));
    checkCudaErrors(cudaMemcpy(d_qhat_modp_list, qhat_modp_list,sizeof(uint64_t*) * beta,cudaMemcpyHostToDevice));



    // =====================================
    // Benchmark
    // =====================================
    if (if_benchmark){
        std::cout << "### Benchmark" << std::endl;
        std::vector<double> elapsed_times;
        for (int i = 0; i < 10; i++)
        {

            // Call kernel
            // Timer start
            auto start = std::chrono::high_resolution_clock::now();
            // const int current_limb = params_h->L;
            const int modup_limb = params_h->KL;
            Mult_1<<<4096, 256, 0>>>(params_d, edge_Init_0_6_Mult_1_0_d, edge_Init_0_7_Mult_1_1_d, edge_Mult_1_0_Add_2_1_d);
            checkCudaErrors(cudaDeviceSynchronize());
            Mult_4<<<4096, 256, 0>>>(params_d, edge_Init_0_4_Mult_4_0_d, edge_Init_0_5_Mult_4_1_d, edge_Mult_4_0_Add_2_0_d);
            checkCudaErrors(cudaDeviceSynchronize());
            Add_2<<<4096, 256, 0>>>(params_d, edge_Mult_4_0_Add_2_0_d, edge_Mult_1_0_Add_2_1_d, edge_Add_2_0_End_3_0_d);
            checkCudaErrors(cudaDeviceSynchronize());
            Mult_5<<<4096, 256, 0>>>(params_d, edge_Init_0_2_Mult_5_0_d, edge_Init_0_3_Mult_5_1_d, edge_Mult_5_0_End_3_1_d);
            checkCudaErrors(cudaDeviceSynchronize());
            Mult_6<<<4096, 256, 0>>>(params_d, edge_Init_0_0_Mult_6_0_d, edge_Init_0_1_Mult_6_1_d, edge_Mult_6_0_End_3_2_d, edge_Mult_6_1_iNTTPhase2_7_0_d);
            checkCudaErrors(cudaDeviceSynchronize());
            iNTTPhase2_7<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_Mult_6_1_iNTTPhase2_7_0_d, edge_iNTTPhase2_7_0_iNTTPhase1_8_0_d);
            checkCudaErrors(cudaDeviceSynchronize());
            iNTTPhase1_8<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_iNTTPhase2_7_0_iNTTPhase1_8_0_d, edge_iNTTPhase1_8_0_MultConst_9_0_d);
            checkCudaErrors(cudaDeviceSynchronize());
            MultConst_9<<<4096, 256, 0>>>(params_d, edge_iNTTPhase1_8_0_MultConst_9_0_d, edge_MultConst_9_0_BConv_35_0_d, edge_MultConst_9_1_BConv_32_0_d, edge_MultConst_9_2_BConv_29_0_d, edge_MultConst_9_3_BConv_26_0_d, edge_MultConst_9_4_BConv_10_0_d, modup_mult, modup_mult_shoup);
            checkCudaErrors(cudaDeviceSynchronize());
            {
                const size_t beta_idx = 4;
                const size_t startPartIdx = params_h->alpha * beta_idx;
                const size_t size_PartQl = (beta_idx == beta - 1)?(params_h->L - params_h->alpha * (beta - 1)): params_h->alpha;
                auto &bconv_pre = drns_tool->v_base_part_Ql_to_compl_part_QlP_conv()[beta_idx];
                auto &ibase = bconv_pre.ibase();
                auto &obase = bconv_pre.obase();
                constexpr int unroll_factor = 2;
                BConv_10<<<params_h->N * obase.size() / 128 / unroll_factor, 128, obase.size() * ibase.size() * sizeof(uint64_t)>>>(params_d, edge_MultConst_9_4_BConv_10_0_d, edge_BConv_10_0_NTTPhase1_11_0_d, bconv_pre.QHatModp(), bconv_pre.ibase().base(), bconv_pre.ibase().size(), bconv_pre.obase().base(), bconv_pre.obase().size(), startPartIdx, size_PartQl);
                checkCudaErrors(cudaDeviceSynchronize());
            }
            NTTPhase1_11<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_BConv_10_0_NTTPhase1_11_0_d, edge_NTTPhase1_11_0_NTTPhase2_12_0_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            NTTPhase2_12<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_NTTPhase1_11_0_NTTPhase2_12_0_d, edge_NTTPhase2_12_0_MultKeyAccum_13_4_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            {
                const size_t beta_idx = 3;
                const size_t startPartIdx = params_h->alpha * beta_idx;
                const size_t size_PartQl = (beta_idx == beta - 1)?(params_h->L - params_h->alpha * (beta - 1)): params_h->alpha;
                auto &bconv_pre = drns_tool->v_base_part_Ql_to_compl_part_QlP_conv()[beta_idx];
                auto &ibase = bconv_pre.ibase();
                auto &obase = bconv_pre.obase();
                constexpr int unroll_factor = 2;
                BConv_26<<<params_h->N * obase.size() / 128 / unroll_factor, 128, obase.size() * ibase.size() * sizeof(uint64_t)>>>(params_d, edge_MultConst_9_3_BConv_26_0_d, edge_BConv_26_0_NTTPhase1_27_0_d, bconv_pre.QHatModp(), bconv_pre.ibase().base(), bconv_pre.ibase().size(), bconv_pre.obase().base(), bconv_pre.obase().size(), startPartIdx, size_PartQl);
                checkCudaErrors(cudaDeviceSynchronize());
            }
            NTTPhase1_27<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_BConv_26_0_NTTPhase1_27_0_d, edge_NTTPhase1_27_0_NTTPhase2_28_0_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            NTTPhase2_28<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_NTTPhase1_27_0_NTTPhase2_28_0_d, edge_NTTPhase2_28_0_MultKeyAccum_13_3_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            {
                const size_t beta_idx = 2;
                const size_t startPartIdx = params_h->alpha * beta_idx;
                const size_t size_PartQl = (beta_idx == beta - 1)?(params_h->L - params_h->alpha * (beta - 1)): params_h->alpha;
                auto &bconv_pre = drns_tool->v_base_part_Ql_to_compl_part_QlP_conv()[beta_idx];
                auto &ibase = bconv_pre.ibase();
                auto &obase = bconv_pre.obase();
                constexpr int unroll_factor = 2;
                BConv_29<<<params_h->N * obase.size() / 128 / unroll_factor, 128, obase.size() * ibase.size() * sizeof(uint64_t)>>>(params_d, edge_MultConst_9_2_BConv_29_0_d, edge_BConv_29_0_NTTPhase1_30_0_d, bconv_pre.QHatModp(), bconv_pre.ibase().base(), bconv_pre.ibase().size(), bconv_pre.obase().base(), bconv_pre.obase().size(), startPartIdx, size_PartQl);
                checkCudaErrors(cudaDeviceSynchronize());
            }
            NTTPhase1_30<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_BConv_29_0_NTTPhase1_30_0_d, edge_NTTPhase1_30_0_NTTPhase2_31_0_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            NTTPhase2_31<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_NTTPhase1_30_0_NTTPhase2_31_0_d, edge_NTTPhase2_31_0_MultKeyAccum_13_2_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            {
                const size_t beta_idx = 1;
                const size_t startPartIdx = params_h->alpha * beta_idx;
                const size_t size_PartQl = (beta_idx == beta - 1)?(params_h->L - params_h->alpha * (beta - 1)): params_h->alpha;
                auto &bconv_pre = drns_tool->v_base_part_Ql_to_compl_part_QlP_conv()[beta_idx];
                auto &ibase = bconv_pre.ibase();
                auto &obase = bconv_pre.obase();
                constexpr int unroll_factor = 2;
                BConv_32<<<params_h->N * obase.size() / 128 / unroll_factor, 128, obase.size() * ibase.size() * sizeof(uint64_t)>>>(params_d, edge_MultConst_9_1_BConv_32_0_d, edge_BConv_32_0_NTTPhase1_33_0_d, bconv_pre.QHatModp(), bconv_pre.ibase().base(), bconv_pre.ibase().size(), bconv_pre.obase().base(), bconv_pre.obase().size(), startPartIdx, size_PartQl);
                checkCudaErrors(cudaDeviceSynchronize());
            }
            NTTPhase1_33<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_BConv_32_0_NTTPhase1_33_0_d, edge_NTTPhase1_33_0_NTTPhase2_34_0_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            NTTPhase2_34<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_NTTPhase1_33_0_NTTPhase2_34_0_d, edge_NTTPhase2_34_0_MultKeyAccum_13_1_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            {
                const size_t beta_idx = 0;
                const size_t startPartIdx = params_h->alpha * beta_idx;
                const size_t size_PartQl = (beta_idx == beta - 1)?(params_h->L - params_h->alpha * (beta - 1)): params_h->alpha;
                auto &bconv_pre = drns_tool->v_base_part_Ql_to_compl_part_QlP_conv()[beta_idx];
                auto &ibase = bconv_pre.ibase();
                auto &obase = bconv_pre.obase();
                constexpr int unroll_factor = 2;
                BConv_35<<<params_h->N * obase.size() / 128 / unroll_factor, 128, obase.size() * ibase.size() * sizeof(uint64_t)>>>(params_d, edge_MultConst_9_0_BConv_35_0_d, edge_BConv_35_0_NTTPhase1_36_0_d, bconv_pre.QHatModp(), bconv_pre.ibase().base(), bconv_pre.ibase().size(), bconv_pre.obase().base(), bconv_pre.obase().size(), startPartIdx, size_PartQl);
                checkCudaErrors(cudaDeviceSynchronize());
            }
            NTTPhase1_36<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_BConv_35_0_NTTPhase1_36_0_d, edge_NTTPhase1_36_0_NTTPhase2_37_0_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            NTTPhase2_37<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_NTTPhase1_36_0_NTTPhase2_37_0_d, edge_NTTPhase2_37_0_MultKeyAccum_13_0_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            MultKeyAccum_13<<<4096, 256, 0>>>(params_d, edge_NTTPhase2_37_0_MultKeyAccum_13_0_d, edge_NTTPhase2_34_0_MultKeyAccum_13_1_d, edge_NTTPhase2_31_0_MultKeyAccum_13_2_d, edge_NTTPhase2_28_0_MultKeyAccum_13_3_d, edge_NTTPhase2_12_0_MultKeyAccum_13_4_d, edge_MultKeyAccum_13_0_iNTTPhase2_20_0_d, edge_MultKeyAccum_13_1_iNTTPhase2_14_0_d, relin_keys);
            checkCudaErrors(cudaDeviceSynchronize());
            iNTTPhase2_14<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_MultKeyAccum_13_1_iNTTPhase2_14_0_d, edge_iNTTPhase2_14_0_iNTTPhase1_15_0_d);
            checkCudaErrors(cudaDeviceSynchronize());
            iNTTPhase1_15<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_iNTTPhase2_14_0_iNTTPhase1_15_0_d, edge_iNTTPhase1_15_0_MultConst_16_0_d);
            checkCudaErrors(cudaDeviceSynchronize());
            MultConst_16<<<4096, 256, 0>>>(params_d, edge_iNTTPhase1_15_0_MultConst_16_0_d, edge_MultConst_16_0_Unknown_17_0_d, moddown_mult, moddown_mult_shoup);
            checkCudaErrors(cudaDeviceSynchronize());
            BConv_general<<<4096, 128>>>(params_d, edge_MultConst_16_0_Unknown_17_0_d, edge_Unknown_17_0_NTTPhase1_18_0_d, moddown_matmul, 15, 3, 0, 15, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            NTTPhase1_18<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_Unknown_17_0_NTTPhase1_18_0_d, edge_NTTPhase1_18_0_NTTPhase2_19_0_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            NTTPhase2_19<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_NTTPhase1_18_0_NTTPhase2_19_0_d, edge_NTTPhase2_19_0_End_3_4_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            iNTTPhase2_20<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_MultKeyAccum_13_0_iNTTPhase2_20_0_d, edge_iNTTPhase2_20_0_iNTTPhase1_21_0_d);
            checkCudaErrors(cudaDeviceSynchronize());
            iNTTPhase1_21<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_iNTTPhase2_20_0_iNTTPhase1_21_0_d, edge_iNTTPhase1_21_0_MultConst_22_0_d);
            checkCudaErrors(cudaDeviceSynchronize());
            MultConst_22<<<4096, 256, 0>>>(params_d, edge_iNTTPhase1_21_0_MultConst_22_0_d, edge_MultConst_22_0_Unknown_23_0_d, moddown_mult, moddown_mult_shoup);
            checkCudaErrors(cudaDeviceSynchronize());
            BConv_general<<<4096, 128>>>(params_d, edge_MultConst_22_0_Unknown_23_0_d, edge_Unknown_23_0_NTTPhase1_24_0_d, moddown_matmul, 15, 3, 0, 15, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            NTTPhase1_24<<<4096, (params_h->n1 / 8) * params_h->pad, (params_h->n1 + params_h->pad + 1) * params_h->pad * sizeof(uint64_t)>>>(params_d, edge_Unknown_23_0_NTTPhase1_24_0_d, edge_NTTPhase1_24_0_NTTPhase2_25_0_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            NTTPhase2_25<<<4096, 128, params_h->per_thread_ntt_size * 128 * sizeof(uint64_t)>>>(params_d, edge_NTTPhase1_24_0_NTTPhase2_25_0_d, edge_NTTPhase2_25_0_End_3_3_d, params_h->ntt_tables->twiddle(), params_h->ntt_tables->twiddle_shoup(), params_h->ntt_tables->modulus());
            checkCudaErrors(cudaDeviceSynchronize());
            // Timer Stop
            checkCudaErrors(cudaDeviceSynchronize());
            auto end = std::chrono::high_resolution_clock::now();


            auto elapsed_usec = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
            std::cout << "Elapsed time: " << elapsed_usec.count() << "us" << std::endl;
            if (i != 0) {elapsed_times.push_back(elapsed_usec.count());}
        }
        std::cout << "Average time[us]: " << std::accumulate(elapsed_times.begin(), elapsed_times.end(), 0.0) / elapsed_times.size() << std::endl;
    }
}
